// =============================================
//  EXPEDIENTES JURÁSICOS — fichas-data.js
//  Datos de las 372 Fichas de Historia
// =============================================

// Categorías según numeración:
// 01–103:   Especie de dominio público
// 104–108:  Empresa implicada
// 109–117:  Personajes que hicieron historia
// 118–198:  De película
// 199–244:  De novela
// 245:      Tributo
// 246–315:  Juguetes
// 316–369:  Videojuegos
// 370–372:  Especiales

var TEXTOS_NARRACION = {
    316: "Desarrollador: BlueSky Software. Distribuidor: Sega. Año: 1993. Descripción: Jurassic Park es un videojuego de acción y aventura desarrollado por BlueSky Software y publicado por Sega para Sega Genesis en 1993. Inspirado en la película y en elementos de la novela de Michael Crichton, destaca por permitir jugar como Dr. Alan Grant o como un Velociraptor, cada uno con habilidades y objetivos diferentes. Historia y jugabilidad: Como Alan Grant, el jugador debe recorrer siete áreas de Isla Nublar, enfrentándose a los dinosaurios mientras busca llegar al Centro de Visitantes y escapar en helicóptero. Para sobrevivir cuenta con diversas armas, munición y botiquines. Como Velociraptor, el jugador es más rápido y puede saltar más alto, aunque solo combate con dientes y garras. Su objetivo es enfrentarse o evadir a los guardias de Jurassic Park y finalmente acorralar a Grant en el Centro de Visitantes, a lo largo de cinco niveles.",
    317: "Desarrollador: DreamWorks Interactive. Distribuidor: Electronic Arts. Año: 1997. Descripción: The Lost World: Jurassic Park es un videojuego de acción en 3D lanzado en 1997 para Sega Saturn y Sony PlayStation. La historia se desarrolla en el Sitio B de InGen, donde más de 20 especies de dinosaurios habitan en medio de un entorno cada vez más caótico. El juego permite controlar diferentes personajes: Como Compsognathus, el jugador debe utilizar su velocidad y capacidad de salto para escapar de grandes depredadores. El Cazador humano cuenta con un amplio arsenal incluyendo tranquilizantes, gas nervioso, lanzallamas y bengalas. Como Velociraptor, el jugador debe defender su territorio de otros dinosaurios. Finalmente, el Tyrannosaurus rex debe utilizar su fuerza para enfrentarse a Velocirraptores, cazadores y otros grandes dinosaurios.",
    318: "Desarrollador: DreamWorks Interactive. Distribuidor: Electronic Arts. Año: 1998. Descripción: Jurassic Park: Trespasser es un videojuego de acción y aventura en primera persona, desarrollado como una continuación de The Lost World: Jurassic Park. Fue lanzado en 1998 para Microsoft Windows y sigue a Anne, la única superviviente de un accidente aéreo ocurrido en Isla Sorna. Historia y jugabilidad: Anne despierta herida en las costas del Sitio B, la antigua instalación de cría de dinosaurios de InGen. Sin ayuda y con un brazo fracturado, debe explorar la isla y utilizar las armas abandonadas por los antiguos trabajadores para defenderse de los dinosaurios mientras busca una forma de escapar. Tras enfrentarse a un Velociraptor alfa, Anne es rescatada en helicóptero y logra regresar a casa.",
    319: "Desarrollador: DreamWorks Interactive. Distribuidor: Electronic Arts. Año: 1999. Descripción: Warpath: Jurassic Park es un videojuego de lucha lanzado para PlayStation en 1999, desarrollado por Black Ops Entertainment en colaboración con DreamWorks Interactive. El juego presenta 14 especies de dinosaurios jugables, de las cuales ocho están disponibles inicialmente y seis deben desbloquearse mediante el Modo Arcade. Cada dinosaurio cuenta con diferentes movimientos y ataques, patrones de coloración y un escenario interactivo propio. Las arenas están inspiradas en diferentes escenarios de las dos primeras películas de la saga, incluyendo lugares de Isla Nublar, Isla Sorna y San Diego, además de una versión del Parque Jurásico de Universal Studios Florida.",
    320: "Desarrollador: Blue Tongue Entertainment. Distribuidores: Vivendi Universal Games y Konami. Año: 2003. Descripción: Jurassic Park: Operation Genesis es un videojuego de simulación y gestión que permite al jugador construir y administrar su propio parque de dinosaurios, con el objetivo de convertirlo en una atracción de cinco estrellas y hacer realidad el sueño de John Hammond. El jugador debe diseñar y administrar todos los aspectos del parque, construyendo instalaciones, caminos, cercas y atracciones, además de encargarse de las necesidades de los dinosaurios. El juego cuenta con 25 especies de dinosaurios, principalmente inspiradas en las criaturas vistas en las películas.",
    321: "Desarrollador: Telltale Games. Año: 2011. Descripción: Jurassic Park: The Game es un videojuego de aventuras episódico en tercera persona. La historia transcurre durante el caos provocado por el fallo del sistema de seguridad de Jurassic Park, presentando nuevos personajes y algunos secundarios conocidos. El jugador explora Isla Nublar mediante una jugabilidad de apuntar y hacer clic, examinando objetos y resolviendo situaciones mientras avanza la historia. También incorpora eventos de tiempo rápido, en los que es necesario pulsar determinadas teclas en el momento adecuado. Uno de los elementos destacados es que el juego intenta resolver algunos acontecimientos que quedaron sin explicación en la película de 1993, incluyendo el destino de la famosa lata de Barbasol de Dennis Nedry.",
    322: "Desarrollador: Ludia. Año: 2015. Descripción: Jurassic World: The Game es un videojuego de simulación, construcción y gestión lanzado en 2015. El juego permite al jugador construir y administrar su propia versión del Jurassic World mostrado en la película, desarrollando instalaciones y creando una colección de dinosaurios y otros animales prehistóricos. El jugador puede obtener criaturas mediante paquetes de cartas, compras y diferentes eventos. El juego también cuenta con la Arena, donde se pueden formar equipos de hasta tres criaturas prehistóricas para enfrentarse a otros equipos en un sistema de combate por turnos.",
    323: "Desarrollador: Ludia. Año: 2018. Descripción: Jurassic World: Alive es un videojuego móvil basado en la tecnología de realidad aumentada y con una jugabilidad similar a Pokémon GO. El juego permite localizar y capturar dinosaurios que deambulan libremente por distintos entornos del mundo real. El jugador debe localizar dinosaurios mediante el mapa y obtener su ADN para llevarlos a centros de protección y estudio del Dinosaur Protection Group. Una de las principales características es la posibilidad de crear híbridos combinando el ADN de diferentes especies para obtener nuevas criaturas que pueden ser utilizadas en batallas.",
    324: "Desarrollador: Frontier Developments. Año: 2018. Descripción: Jurassic World: Evolution es un videojuego de gestión y construcción de parques. El jugador toma el control de Isla Nublar y el Archipiélago de las Cinco Muertes, donde deberá construir y administrar su propio Jurassic World. El objetivo es desarrollar un parque funcional mediante la construcción de atracciones, instalaciones de seguridad y centros de investigación, mientras se utiliza la bioingeniería para crear y modificar diferentes especies de dinosaurios. Cada decisión influye en el desarrollo del parque y puede generar nuevos desafíos.",
    325: "Acrocanthosaurus aparece como uno de los dinosaurios jugables en Warpath: Jurassic Park, donde se presenta como un gran depredador capaz de enfrentarse a otras especies dentro de los combates del juego. Su estilo de combate comparte el mismo conjunto de movimientos que el Tyrannosaurus rex y el Cryolophosaurus, por lo que sus ataques están enfocados principalmente en la fuerza y los enfrentamientos directos. Su escenario principal es la gasolinera Unocal 76, una de las localizaciones inspiradas en los acontecimientos de The Lost World: Jurassic Park. Dentro del juego, Acrocanthosaurus cuenta con tres patrones de coloración diferentes: verde, marrón y una combinación de blanco y naranja.",
    326: "Giganotosaurus aparece como uno de los dinosaurios jugables de Warpath: Jurassic Park, donde fue incluido como uno de los grandes depredadores disponibles para los combates. Curiosamente, su nombre aparece escrito de forma incorrecta como Giganotasaurus, mientras que dentro de los archivos y códigos del juego se le identifica con el nombre clave Giga. El dinosaurio cuenta con tres patrones de coloración: azul, marrón y una variante de blanco con rojo. Su escenario de combate es el recinto del T. rex, una de las localizaciones más reconocibles del juego y basada en las instalaciones de Jurassic Park.",
    327: "El Tyrannosaurus rex es uno de los ocho personajes disponibles desde el inicio en el juego de lucha Warpath: Jurassic Park, siendo uno de los dinosaurios más representativos del título y de la propia franquicia. Su coloración principal es azul, inspirada en uno de los pósteres promocionales de The Lost World: Jurassic Park. Cuenta además con una variante verde, basada en el macho de The Lost World conocido como Buck, y una tercera variante verde agua con manchas amarillas de patrón atigrado. Su arena principal es la cubierta del S.S. Venture, el barco utilizado para transportar al T. rex desde Isla Sorna hasta San Diego.",
    328: "Suchomimus aparece como uno de los dinosaurios jugables de Warpath: Jurassic Park. Dentro de los archivos del juego, se le identifica con el nombre clave Sucho. Su escenario principal es la Puerta de Visitantes de Isla Nublar. Uno de los detalles más curiosos de su diseño es su cabeza, que presenta un aspecto muy similar a la del Baryonyx visto en el videojuego de The Lost World: Jurassic Park. También destaca por su tamaño exagerado dentro del juego: Suchomimus es representado como un dinosaurio incluso más grande que el Tyrannosaurus rex. Cuenta con tres patrones de coloración: gris, morado azulado y verde oscuro.",
    329: "Ankylosaurus aparece como uno de los dinosaurios jugables en Warpath: Jurassic Park, donde forma parte del elenco de especies disponibles para los combates. Su presencia permite incorporar al juego uno de los herbívoros acorazados más representativos de la franquicia. Su escenario principal de combate es el Centro de Visitantes de Isla Nublar, una de las localizaciones más emblemáticas de Jurassic Park. Dentro del juego, Ankylosaurus cuenta con tres patrones de coloración: blanco, negro y amarillo, y plateado.",
    330: "Styracosaurus aparece como un dinosaurio inicial jugable en Warpath: Jurassic Park. Dentro del juego, comparte el mismo conjunto de movimientos que Triceratops, por lo que su estilo de combate es muy similar, basándose principalmente en embestidas y ataques con su característico cuerno. Cuenta con tres patrones de coloración disponibles: aguamarina, naranja y morada. Su inclusión amplía la variedad de ceratópsidos jugables y ofrece una alternativa visual al Triceratops.",
    331: "Cryolophosaurus aparece en Warpath: Jurassic Park como uno de los seis dinosaurios desbloqueables del juego. Se obtiene después de desbloquear a Triceratops y justo antes de Albertosaurus. Su escenario de combate es un valle desértico. Sus ataques se caracterizan por ser rápidos, aunque relativamente débiles. Una de sus características más llamativas es que, en lugar de utilizar sus mandíbulas para atacar, este Cryolophosaurus emplea su cresta como arma ofensiva. Cuenta con tres patrones de coloración: negro, naranja claro y verde.",
    332: "Triceratops es uno de los dinosaurios jugables de Warpath: Jurassic Park, siendo uno de los seis dinosaurios desbloqueables. Dentro del juego, comparte el mismo estilo de combate y patrón de movimientos que Styracosaurus, basando sus ataques principalmente en embestidas y el uso de sus cuernos para enfrentarse a sus oponentes. Cuenta con tres patrones de coloración: rojo, verde y morado. Su arena de batalla es el campamento de InGen, una localización inspirada en las instalaciones que aparecen en The Lost World: Jurassic Park.",
    333: "Albertosaurus aparece en Warpath: Jurassic Park como el último dinosaurio que puede desbloquearse dentro del juego. Su inclusión amplía el grupo de grandes depredadores disponibles y representa una de las últimas recompensas para los jugadores que avanzan en el modo de desbloqueo. Su arena de combate está ambientada en Universal Studios. Comparte el mismo patrón de movimientos que Carcharodontosaurus y Giganotosaurus, utilizando ataques rápidos y físicos propios de los grandes terópodos. Cuenta con tres patrones de coloración: escarlata, verde bosque y canela.",
    334: "Tyrannosaurus es un dinosaurio carnívoro de 5 estrellas en Jurassic Park: Operation Genesis, cuya apariencia en el juego está basada en su representación de Jurassic Park III. Es el tercer carnívoro más grande del juego, alcanzando aproximadamente 13 metros dentro del juego. Es un depredador que atemoriza a prácticamente todos los herbívoros y pequeños carnívoros, aunque el Spinosaurus no se deja intimidar. Ambos pueden enfrentarse en combates donde cualquiera de los dos puede resultar vencedor. Gracias a su enorme fuerza y capacidad depredadora, Tyrannosaurus puede abatir fácilmente a la mayoría de los demás dinosaurios.",
    335: "Acrocanthosaurus es un gran dinosaurio carnívoro de 4 estrellas en Jurassic Park: Operation Genesis, procedente del Cretácico y localizado en la Formación Hell Creek A. Destaca como un depredador capaz de enfrentarse a otros grandes carnívoros y cazar una amplia variedad de presas, incluyendo ceratópsidos, hadrosáuridos y, de forma exclusiva dentro del juego, Camarasaurus. Su presa favorita es el Parasaurolophus. El juego representa a Acrocanthosaurus con una cresta dorsal o vela muscular, con una coloración similar a la arena del desierto, manchas blancas en la cabeza y franjas rojas a lo largo de la vela.",
    336: "Allosaurus es un dinosaurio carnívoro de 4 estrellas en Jurassic Park: Operation Genesis, representado con una coloración entre naranja y marrón y que suele habitar en zonas boscosas. Vivió durante el Jurásico Superior y alcanzaba aproximadamente 11 metros de longitud. En el juego, es representado como uno de los grandes carnívoros más débiles y menos agresivos, ya que rara vez se enfrenta a depredadores como Tyrannosaurus o Spinosaurus. Es un depredador rápido y versátil, capaz de cazar especies como Camarasaurus y Stegosaurus.",
    337: "Camarasaurus es un saurópodo de 3 estrellas en Jurassic Park: Operation Genesis que vivió durante el Jurásico Superior y puede encontrarse en la Formación Morrison B. Su principal compañero es Brachiosaurus, ya que son los únicos saurópodos disponibles en el juego. También puede convivir favorablemente con otros herbívoros jurásicos, como Dryosaurus, Stegosaurus y Kentrosaurus. Camarasaurus destaca por su capacidad para aumentar rápidamente los niveles de diversión de las atracciones, especialmente cuando varios individuos socializan.",
    338: "Carcharodontosaurus es un dinosaurio carnívoro de 4 estrellas en Jurassic Park: Operation Genesis que vivió durante el Cretácico Inferior. Presenta una coloración negra, con la parte inferior del cuerpo entre gris y blanco, además de unas crestas rojas sobre los ojos. Es un dinosaurio muy territorial y agresivo, considerado uno de los carnívoros más destructivos del juego. Puede abatir grandes dinosaurios como Camarasaurus, Triceratops, Spinosaurus e incluso Tyrannosaurus en apenas un par de mordidas. Es el segundo carnívoro más largo del juego, solo por detrás de Spinosaurus.",
    339: "Dryosaurus es el único dinosaurio de 1 estrella del juego Jurassic Park: Operation Genesis y, por lo general, es una de las primeras especies que los jugadores pueden obtener. Es una especie gregaria, que suele desplazarse en grupos junto a otros individuos de su misma especie, de manera similar a Gallimimus. Esta conducta grupal constituye prácticamente su único mecanismo de defensa, por lo que puede convertirse fácilmente en presa de carnívoros más rápidos, como Velociraptor.",
    340: "Homalocephale es un pequeño dinosaurio herbívoro que vivió durante el Cretácico Superior y aparece en Jurassic Park: Operation Genesis. A pesar de poseer un cráneo relativamente grueso, no cuenta con la capacidad de defenderse de los depredadores, por lo que huye de los carnívoros o permanece cerca de herbívoros de mayor tamaño para obtener protección. Es una especie relativamente popular entre los visitantes y puede integrarse bien en comunidades formadas por otros herbívoros pequeños.",
    341: "Torosaurus es un ceratópsido de 2 estrellas en Jurassic Park: Operation Genesis que puede defenderse de los depredadores y prefiere vivir en pequeñas manadas de alrededor de cinco individuos. Suele convivir con otros miembros de su familia, como Styracosaurus y Triceratops. Al igual que Triceratops, Torosaurus es capaz de matar a un Velociraptor de un solo golpe, convirtiéndose en un herbívoro bastante eficaz para defenderse de pequeños depredadores.",
    342: "Styracosaurus es un pequeño herbívoro de 2 estrellas en Jurassic Park: Operation Genesis que vivió durante el Cretácico Superior. Utiliza su característico cuerno nasal para defenderse de los pequeños carnívoros, aunque en el juego suele pasar más tiempo corriendo en círculos alrededor de ellos y emitiendo gruñidos que atacándolos directamente. Es una especie gregaria, que normalmente se desplaza en manadas junto a Torosaurus y Triceratops.",
    343: "El Deinonychus es un género de terópodo que existió hace unos 110 millones de años, durante el Cretácico inferior. Su nombre significa garra terrible, en referencia a la larga garra en forma de guadaña que tiene en el segundo dedo de los pies traseros. Es pariente cercano del Velociraptor y puede llegar a medir hasta 3 metros de largo. Sus primeros fósiles fueron descubiertos en 1931 por Barnum Brown en la formación Cloverly, en Montana. El Deinonychus vivía en las llanuras aluviales del oeste de los Estados Unidos y Canadá, coexistiendo con dinosaurios como el Acrocanthosaurus y el Sauropelta.",
    344: "El Dracorex es un herbívoro de la familia de los paquicefalosáuridos que se caracteriza por sus grandes cuernos y su cráneo rugoso. Su nombre significa rey dragón. El Dracorex medía aproximadamente 3,5 metros de largo y tenía un peso superior a los 600 kilogramos, con un cráneo acorazado que lo protegía de los depredadores. Fue descubierto en 2004 en la formación Hell Creek de Dakota del Sur, cuando tres paleontólogos aficionados encontraron un cráneo parcial. El Dracorex vivió en Norteamérica durante el Cretácico superior, hace aproximadamente 65 a 70 millones de años.",
    345: "El Edmontosaurus es un género de dinosaurio hadrosáurido herbívoro caracterizado por su boca en forma de pico. Con 9 metros de longitud y más de tres toneladas de peso, es uno de los hadrosáuridos de mayor tamaño, pero puede alcanzar los 50 kilómetros por hora para escapar de los depredadores. Los primeros huesos de Edmontosaurus fueron descubiertos en 1891 por John Bell Hatcher en la formación Lance de Wyoming. El Edmontosaurus vivió durante el Cretácico superior, hace unos 65 a 75 millones de años, coexistiendo con dinosaurios como el Triceratops, el Albertosaurus y el Pachycephalosaurus.",
    346: "El Metriacanthosaurus es un género de terópodo carnívoro que existió durante el Jurásico superior. Su nombre significa lagarto moderadamente espinoso, en referencia a las espinas de sus vértebras, y puede llegar a medir hasta 8 metros de largo, con un peso superior a una tonelada. Fue descrito por primera vez por Friedrich von Huene en 1923 y reclasificado finalmente como Metriacanthosaurus en 1964 por el paleontólogo inglés Alick Walker. El Metriacanthosaurus vivió hace unos 160 millones de años en la costa meridional de Inglaterra.",
    347: "El Carcharodontosaurus es un dinosaurio terópodo carnívoro que existió durante el Cretácico superior, hace unos 95 a 100 millones de años. Con una longitud cercana a los 15 metros, es uno de los terópodos más grandes y debe su nombre, que significa lagarto de dientes serrados, a la forma de sus dientes de hasta 20 centímetros. Descubrimiento: Charles Depéret y Justin Savornin descubrieron formalmente este género en 1925. En 1931, el paleontólogo alemán Ernst Stromer vinculó los dientes con un cráneo parcial y otros huesos descubiertos en 1914, aunque estos hallazgos fueron destruidos durante la Segunda Guerra Mundial. Paleoecología: El Carcharodontosaurus vivía en el clima cálido y húmedo del norte de África, disputándose el territorio cerca de ríos y lagos con otros grandes dinosaurios como el Spinosaurus. Este apareció dentro del paquete de dinosaurios del Cretácico.",
    348: "Con un peso de cerca de siete toneladas y una longitud de hasta 11 metros, el Deinocheirus es el ornitomimosaurio más grande que haya existido. Este género se remonta aproximadamente 70 millones de años al período cretácico superior y su nombre se traduce como mano horrible, en referencia a sus grandes y poderosas garras. Fue descubierto por primera vez en 1965 por Zofia Kielan-Jaworowska en la región de la Cuenca de Nemegt del desierto del Gobi. El Deinocheirus vivió cerca de los ríos Nemegt en la Mongolia actual. Este apareció en el videojuego Jurassic World Evolution 2 dentro del paquete de especies con plumas.",
    349: "El Shonisaurus es un ictiosaurio del periodo triásico superior notable por su increíble tamaño, ya que es uno de los reptiles marinos más grandes de la historia. Podía llegar a alcanzar 15 metros de longitud y casi 30 toneladas de peso. Los primeros restos de Shonisaurus se desenterraron en 1920 en las montañas Shoshone en Nevada, Estados Unidos, de las cuales recibe su nombre. El género se nombró oficialmente en 1976, 56 años después de su descubrimiento inicial. El Shonisaurus vivió entre hace 225 y 240 millones de años en océanos profundos. Este apareció en el videojuego Jurassic World Evolution 2 dentro del paquete de especies marinas prehistóricas.",
    350: "Originario de Sudamérica, el Thanatosdrakon es un pterosaurio grande que se remonta al periodo Cretácico superior, hace alrededor de 86 a 89 millones de años. Con una envergadura de aproximadamente 9 metros, es el pterosaurio más grande conocido que haya habitado Sudamérica. Su nombre se traduce como el dragón de la muerte. El primer espécimen se desenterró en la Formación Plottier en la región de Mendoza en Argentina en 2018. Este género coexistió junto con otros dinosaurios y diversa fauna por los ríos y las llanuras aluviales de la región de Neuquén. Este apareció en el videojuego Jurassic World Evolution 2 dentro del paquete de colección para administradores de parques.",
    351: "El Patagotitan es un saurópodo titanosaurio que alcanzaba las 50 toneladas de peso y unos 30 metros de longitud. Vivió durante el periodo Cretácico y debe su nombre a la región de Sudamérica en la que fue descubierto. Cuando se descubrió este holotipo, el Patagotitan se convirtió en el saurópodo de mayor tamaño que jamás se había encontrado. La primera prueba de su existencia fue un fragmento descubierto por Aurelio Hernández, lo que llevó a expediciones que encontraron más fósiles entre 2012 y 2015. El Patagotitan cohabitaba con diversos grupos de saurópodos y herbívoros, y también anidaba en grupos, con 15 a 40 huevos por puesta. Este apareció en el videojuego Jurassic World Evolution 3 dentro del juego base.",
    352: "El Troodon fue clonado por la Dra. Laura Sorkin en Isla Nublar utilizando únicamente ADN de dinosaurio. Era similar a los dromeosáuridos, aunque de menor tamaño, con brazos largos, cola rígida, garras en forma de hoz y pequeñas estructuras plumosas. Su coloración era gris azulada con vientre rojizo y presentaba grandes ojos adaptados a la oscuridad. Vivía en manadas de unos diez individuos y poseía una inteligencia comparable a la de los Velociraptor. Su principal arma era una mordedura venenosa que provocaba desorientación, alucinaciones y convulsiones. Debido a su comportamiento sigiloso y peligroso, John Hammond ordenó su eliminación, pero la Dra. Sorkin decidió ocultarlos en los corrales de cuarentena de Isla Nublar.",
    353: "Al menos cuatro Herrerasaurus fueron creados por InGen en su complejo de Isla Sorna y posteriormente trasladados a Isla Nublar, donde fueron alojados en un recinto propio destinado a la primera fase de Jurassic Park. La Dra. Laura Sorkin consideraba que los Herrerasaurus fueron creados como una alternativa más segura al Velociraptor. Los clones presentaban un cuerpo rojo brillante con rayas rojo oscuro, vientre blanco y manchas amarillas. Se desplazaban en manadas y destacaban por su capacidad para perseguir a sus presas durante largas distancias.",
    354: "El Tylosaurus es un reptil marino clonado que habitaba en una instalación de Isla Nublar en Jurassic Park: The Game. La Dra. Laura Sorkin decidió liberarlo con la esperanza de que pudiera sobrevivir en libertad, pero el animal embistió la rotonda de la instalación y provocó que Sorkin cayera a la piscina inferior, donde fue devorada por el reptil. Cuando la instalación comenzó a inundarse, Gerry Harding, Jess y Nima tuvieron que atravesar la enorme laguna para escapar. Finalmente, Gerry Harding utilizó un rifle tranquilizante para cerrar la puerta de la cueva, dejando al Tylosaurus atrapado en la laguna y permitiendo que el grupo escapara.",
    355: "El T-Rex Alfa de Jurassic Park: Trespasser es una hembra de Tyrannosaurus rex de enormes proporciones, considerada el ejemplar más grande y poderoso de los Siete Soberanos clonados en Isla Sorna. Presenta una característica coloración rojiza y negra, acompañada de rayas similares a las de un tigre. Alcanza aproximadamente 6 metros de altura y 16,5 metros de longitud, superando considerablemente las dimensiones de otros tiranosaurios presentes en la isla. Es representada como un depredador extremadamente agresivo, dominante e imponente, capaz de controlar su territorio y enfrentarse a otros grandes depredadores.",
    356: "El Velociraptor Alfa de Jurassic Park: Trespasser es el líder de la Tribu C, una manada que habita en las zonas montañosas de Isla Sorna, particularmente en la cima del Monte Watson. Este ejemplar presenta una mutación genética que provocó un gigantismo excepcional, alcanzando un tamaño muy superior al de un Velociraptor convencional y acercándose en dimensiones a las de un Albertosaurus. Su cuerpo posee una distintiva coloración rojiza con rayas negras, similar al patrón de un tigre. Su enorme tamaño, comportamiento dominante y posición dentro de la manada lo convierten en uno de los depredadores más imponentes de Trespasser.",
    357: "El Parasaurolophus de Jurassic Park: Trespasser es un herbívoro pacífico que habita en distintas zonas de Isla Sorna durante el recorrido de Anne. Generalmente es dócil y, cuando Anne intenta acercarse, los ejemplares suelen dispersarse y huir. A diferencia de sus representaciones cinematográficas, presenta un cuerpo de color naranja brillante con manchas negras distribuidas por toda la piel. Además, posee una característica única dentro de la saga: una membrana de piel que cuelga desde la cresta hacia la parte posterior de la cabeza. Este rasgo apareció por primera vez en Trespasser y no volvió a utilizarse posteriormente en la franquicia.",
    358: "El Leptoceratops aparece en The Lost World: Jurassic Park durante los niveles en los que el jugador controla a un Compsognathus, específicamente en High Ridge y Rainforest. En ambas zonas, actúa como guardián del ADN de dinosaurio. Debido a su gran tamaño en comparación con el Compsognathus, puede causar una cantidad considerable de daño. Su principal ataque consiste en un movimiento de embestida y corneada con la cabeza. Su diseño presenta una coloración turquesa brillante, con patrones azul oscuro alrededor de los ojos, cuello, codos y rodillas, además de un vientre marrón crema.",
    359: "El Baryonyx aparece en el videojuego The Lost World: Jurassic Park, donde habitaba en el Hábitat B de Isla Sorna junto con Staurikosaurus y Dimorphodon. Su presencia se encuentra principalmente en cuevas costeras, escenario que puede explorarse durante el nivel Human Hunter. En el juego, el Baryonyx es representado como un animal territorial y extremadamente agresivo, atacando a cualquier intruso que se aproxime a su territorio. El diseño de la cabeza del Suchomimus en Warpath: Jurassic Park guarda un notable parecido con el Baryonyx de The Lost World: Jurassic Park.",
    360: "En The Lost World: Jurassic Park, el Carnotaurus aparece únicamente en el nivel de Compsognathus llamado Sleeping Titan. En esta sección, el dinosaurio es invulnerable y no puede ser eliminado. Para avanzar, el jugador debe maniobrar alrededor del Carnotaurus y evitar enfrentarlo directamente, ya que intentar huir corriendo provocará que el gigantesco depredador devore al Compsognathus controlado por el jugador.",
    361: "El Lythronax fue añadido a Jurassic World: The Game el 22 de marzo de 2019 como un carnívoro legendario de torneo. Pertenece a la categoría de dinosaurios terrestres y puede desbloquearse al obtener un paquete de Lythronax mediante la ruleta o al quedar dentro del 1 por ciento superior de su torneo. Una vez desbloqueado, pueden adquirirse ejemplares adicionales en el mercado por 7,050 ADN. Cada ejemplar alcanza una tasa máxima de generación de 315.8 monedas por minuto. Desde el 14 de febrero de 2020, un Lythronax de nivel 40 puede fusionarse con un Glyptodon de nivel 40 para crear al híbrido Glythronax.",
    362: "El Einiosaurus es una especie herbívora legendaria de torneo disponible en Jurassic World: The Game. Es un dinosaurio no híbrido y pertenece a la categoría Jurassic. Para desbloquearlo, el jugador debe obtener un paquete de Einiosaurus mediante la ruleta o quedar dentro del 1 por ciento superior del torneo. Una vez desbloqueado, pueden adquirirse ejemplares adicionales por 6,750 ADN en el mercado. Su tiempo de incubación es de 7 horas, tiene un costo de colocación de 6,750 ADN y proporciona una recompensa de 3,375 ADN al venderlo. Su tasa máxima de generación de ingresos es de 328 monedas por minuto.",
    363: "El Ornithocheirus es un pterosaurio legendario de torneo disponible en Jurassic World: The Game. Se trata de una criatura no híbrida perteneciente a la categoría de pterosaurios. Para desbloquearlo, el jugador debe obtener un paquete de Ornithocheirus mediante la ruleta o quedar dentro del 1 por ciento superior de su torneo. Una vez desbloqueado, pueden adquirirse ejemplares adicionales en el mercado por 7,850 ADN o conseguirse mediante los paquetes de cartas de Jurassic World: The Game.",
    364: "El Plesiosaurus fue añadido al Parque Acuático de Jurassic World: The Game el 16 de marzo de 2016 como una criatura acuática legendaria no híbrida, perteneciente a las especies de superficie. Se desbloquea al completar la Batalla 62. Una vez obtenido, pueden adquirirse ejemplares adicionales en el mercado por 4,500 ADN. Su tiempo de incubación es de 3 días y 23 horas, mientras que su colocación cuesta 4,500 ADN y proporciona 2,250 ADN al venderlo. Su tasa máxima de generación de ingresos alcanza las 201.6 monedas por minuto.",
    365: "El Dunkleosteus fue añadido al Parque Acuático de Jurassic World: The Game el 11 de diciembre de 2015 como una criatura acuática legendaria de clase Cueva y no híbrida. Se desbloquea al completar su evento de batalla. Una vez obtenido, pueden adquirirse ejemplares adicionales en el mercado por 4,200 ADN. Desde el 20 de noviembre de 2018, un Dunkleosteus de nivel 40 puede fusionarse con un Mosasaurus de nivel 40 para crear el híbrido Dunkleosaurus. Su tasa máxima de generación de ingresos es de 188 monedas por minuto.",
    366: "El Ophthalmosaurus es una criatura acuática legendaria de torneo disponible en Jurassic World: The Game. Pertenece a la clase Arrecife y puede alcanzar el nivel 40, donde presenta 3,160 de salud, 988 de daño y 1,976 de ferocidad. Su costo en el mercado es de 8,250 ADN, mientras que vender un ejemplar de nivel 1 proporciona 4,130 ADN. Su tiempo de incubación es de 7 días y genera hasta 449 monedas por minuto. Además, el Ophthalmosaurus es utilizado como componente para crear al superhíbrido Ophthacerapsis, mediante su combinación con un Diploceraspis.",
    367: "El Woolly Mammoth fue añadido al Parque Cenozoico de Jurassic World: The Game el 15 de diciembre de 2016 como una criatura legendaria de torneo, no híbrida y perteneciente a la clase Nieve. Se desbloquea al obtener un paquete de Woolly Mammoth mediante la ruleta o al quedar dentro del 1 por ciento superior de su torneo. Una vez desbloqueado, pueden adquirirse ejemplares adicionales en el mercado por 10,000 ADN. Su tasa máxima de generación de ingresos es de 560 monedas por minuto. Además, un Woolly Mammoth de nivel 40 puede fusionarse con un Elasmotherium de nivel 40 para crear el híbrido Mammotherium.",
    368: "El Phorusrhacos fue añadido a la Biosfera de Jurassic World: The Game el 15 de febrero de 2017 como una criatura cenozoica superrara, perteneciente a la clase Sabana y no híbrida. Se desbloquea al completar su evento de batalla llamado Glacial Shift. Una vez obtenido, pueden adquirirse ejemplares adicionales en el mercado por 3,000 ADN. Su tasa máxima de generación de ingresos es de 192 monedas por minuto.",
    370: "Michael Crichton (1942–2008) fue un médico, escritor, guionista y cineasta estadounidense, reconocido como uno de los principales impulsores del tecno-thriller. Escribió las novelas Parque Jurásico y El mundo perdido, además de colaborar en sus adaptaciones cinematográficas. Estudió literatura y medicina en Harvard y, aunque inicialmente se inclinó por la medicina, desarrolló una gran pasión por la escritura. La idea de Jurassic Park surgió a partir de un proyecto sobre la clonación de un pterodáctilo mediante ADN fósil. Crichton consideró que la historia necesitaba una base científica más convincente, por lo que investigó durante varios años hasta desarrollar la idea de un millonario que utilizara la ingeniería genética para crear un parque de animales prehistóricos. Para desarrollar esta premisa, tomó inspiración de las investigaciones del paleobiólogo George Poinar Jr. sobre la conservación de material biológico en ámbar fosilizado. Más allá de los dinosaurios, Crichton utilizó Jurassic Park para explorar los peligros de la manipulación genética, la arrogancia científica y el intento de controlar la naturaleza. Su trabajo convirtió a Jurassic Park en una obra fundamental de la ciencia ficción.",
    371: "Steven Allan Spielberg, nacido en Cincinnati, Ohio, el 18 de diciembre de 1946, es un director, guionista y productor estadounidense, considerado uno de los cineastas más influyentes de la industria. Fue una figura clave en la saga Jurassic Park, dirigiendo sus dos primeras películas y participando como productor ejecutivo en las posteriores. Ha sido nominado siete veces al Óscar a Mejor Director, ganándolo por La lista de Schindler en 1993 y Saving Private Ryan en 1998. En 1989, Spielberg conoció a Michael Crichton, quien le habló de su novela sobre dinosaurios clonados. Fascinado por la idea, impulsó a Universal Pictures a adquirir los derechos antes de su publicación. Spielberg vio en la historia una especie de Tiburón en tierra, combinando suspenso, acción y dinosaurios. Con el apoyo de Industrial Light and Magic y los efectos animatrónicos y digitales, logró llevar la visión de Crichton a la pantalla y convertir Jurassic Park en un referente del cine.",
    372: "Mr. ADN fue un personaje creado por InGen con una finalidad principalmente educativa dentro de Jurassic Park. Su función era ayudar a los visitantes a comprender, de una manera sencilla y entretenida, los complejos procesos científicos empleados para la creación de los dinosaurios del parque. El personaje formaba parte de la experiencia que InGen había preparado para los visitantes antes de que comenzaran sus recorridos por las instalaciones. Antes de cada visita guiada, los visitantes se dirigían al cine del Centro de Visitantes, donde se proyectaba una película protagonizada por el Sr. ADN y John Hammond. A través de esta presentación, ambos explicaban de forma simplificada cómo InGen había conseguido obtener material genético de dinosaurios y utilizarlo para devolver estas criaturas a la vida. De esta manera, el Sr. ADN servía como una especie de guía científica y mascota de Jurassic Park.",
    369: "La Titanoboa fue añadida al Parque Cenozoico de Jurassic World: The Game el 24 de noviembre de 2017 como una criatura cenozoica legendaria de torneo, no híbrida y perteneciente a la clase Caverna. Se desbloquea al obtener un paquete de Titanoboa mediante la ruleta o al quedar dentro del 1 por ciento superior de su torneo. Una vez desbloqueada, pueden adquirirse ejemplares adicionales en el mercado por 11,150 ADN. Su tasa máxima de generación de ingresos es de 499 monedas por minuto.",
};


function getFichaCategoria(num) {
    if (num >= 1   && num <= 103) return { label: 'ESPECIE',     clase: 'cat-especie',     color: '#00e5b0' };
    if (num >= 104 && num <= 108) return { label: 'EMPRESA',     clase: 'cat-empresa',     color: '#ff6b00' };
    if (num >= 109 && num <= 117) return { label: 'PERSONAJE',   clase: 'cat-personaje',   color: '#d4a017' };
    if (num >= 118 && num <= 198) return { label: 'PELÍCULA',    clase: 'cat-pelicula',    color: '#ff3030' };
    if (num >= 199 && num <= 244) return { label: 'NOVELA',      clase: 'cat-novela',      color: '#b080ff' };
    if (num === 245)              return { label: 'TRIBUTO',     clase: 'cat-tributo',     color: '#ffd700' };
    if (num >= 246 && num <= 315) return { label: 'JUGUETES',    clase: 'cat-juguetes',    color: '#00cfff' };
    if (num >= 316 && num <= 369) return { label: 'VIDEOJUEGOS', clase: 'cat-videojuegos', color: '#ff007f' };
    if (num >= 370 && num <= 372) return { label: 'ESPECIALES',  clase: 'cat-especiales',  color: '#c0c0ff' };
    return { label: '???', clase: 'cat-unknown', color: '#607868' };
}

// Sonidos SOLO para fichas de Especie (001 a 103) y Personaje (109 a 117)
function getFichaSonido(numInt, numStr) {
    if ((numInt >= 1 && numInt <= 103) || (numInt >= 109 && numInt <= 117)) {
        return numStr + '.mp4';
    }
    return null;
}

// Narraciones de IA disponibles para todas las fichas
function getFichaNarracion(numInt, numStr) {
    if (numInt >= 1 && numInt <= 372) {
        return 'narracion_' + numStr + '.mp3';
    }
    return null;
}

// Videos para fichas de 118 a 198
function getFichaVideo(numInt, numStr) {
    if (numInt >= 118 && numInt <= 198) {
        return numStr + '.mp4';
    }
    return null;
}

// Fichas que tienen una variante (doble clic para cambiar)
var FICHAS_CON_VARIANTE = { 6: true, 111: true, 137: true, 262: true, 331: true, 343: true };

// Genera el array de 372 fichas
var FICHAS = (function() {
    var arr = [];
    for (var i = 1; i <= 372; i++) {
        var cat = getFichaCategoria(i);
        var num = String(i).padStart(3, '0');
        var tieneVariante = !!(typeof FICHAS_CON_VARIANTE !== 'undefined' && FICHAS_CON_VARIANTE[i]);
        arr.push({
            id: i,
            num: num,
            categoria: cat.label,
            clase: cat.clase,
            color: cat.color,
            frenteImg: 'fichas/frente_' + num + '.jpg',
            reversoImg: 'fichas/reverso_' + num + '.jpg',
            varianteFrenteImg: tieneVariante ? 'fichas/variante_frente_' + num + '.jpg' : null,
            varianteReversoImg: tieneVariante ? 'fichas/variante_reverso_' + num + '.jpg' : null,
            tieneVariante: tieneVariante,
            sonido: getFichaSonido(i, num),
            narracion: getFichaNarracion(i, num),
            textoNarracion: (typeof TEXTOS_NARRACION !== 'undefined' && TEXTOS_NARRACION[i]) ? TEXTOS_NARRACION[i] : null,
            video: getFichaVideo(i, num)
        });
    }
    return arr;
})();

