// SPECIES DATA PART 2 — G through P
var SPECIES_PART2 = [
    {
        name: "Gorgonopsid",
        key: "GP-81267",
        family: "Gorgonopsidae",
        diet: "carnivoro",
        dietLabel: "CARNÍVORO",
        height: "1.2 m",
        length: "3 m",
        weight: "500 kg",
        location: "Isla Matanceros",
        emoji: "🐺",
        ingen: "Terápsido carnívoro con colmillos prominentes. Clonado en Isla Matanceros.",
        desc: "Clonado en Isla Matanceros. Terápsido carnívoro con colmillos prominentes.",
        extra: "Los gorgonópsidos fueron los depredadores dominantes del Pérmico tardío, emparentados lejanamente con los mamíferos. Su rasgo más notable son los enormes colmillos en dientes de sable que les daban aspecto de tigre de dientes de sable prehistórico. InGen los clonó para el 'Proyecto Primigenio', un subproyecto de Re-Genesis centrado en fauna del Pérmico. Son técnicamente no-dinosaurios pero fueron incluidos por su valor científico y exhibicional. Paradero actual desconocido."
    },
    {
        name: "Herrerasaurus",
        key: "HR-75031",
        family: "Herrerasauridae",
        diet: "carnivoro",
        dietLabel: "CARNÍVORO",
        height: "1.2 m",
        length: "4 m",
        weight: "210 kg",
        location: "Isla Nublar",
        emoji: "🦖",
        ingen: "Llevado a Nublar para Fase 2. Depredador ágil y oportunista. Presentan enanismo.",
        desc: "Llevado a Nublar para Fase 2. Depredador ágil y oportunista.",
        extra: "El Herrerasaurus ischigualastensis del Triásico tardío de Argentina es uno de los dinosaurios carnívoros más primitivos conocidos. Su posición filogenética exacta aún es debatida. Los especímenes InGen destinados a Nublar para la Fase 2 mostraron un comportamiento oportunista, capturando presas de hasta el doble de su peso. Eran activos en penumbra y amanecer, lo que dificultaba su monitoreo con los sistemas de vigilancia existentes en la isla."
    },
    {
        name: "Hypsilophodon",
        key: "HS-21567",
        family: "Hypsilophodontidae",
        diet: "herbivoro",
        dietLabel: "HERBÍVORO",
        height: "1 m",
        length: "2.3 m",
        weight: "68 kg",
        location: "Isla Sorna",
        emoji: "🦘",
        ingen: "Clonado en Sorna. Baja tasa de fallos embrionarios.",
        desc: "El Hypsilophodon fue clonado en Isla Sorna como parte del programa de diversificación de herbívoros menores. Su ADN fue reconstruido con relativa estabilidad, con una de las tasas más bajas de fallos embrionarios entre las especies pequeñas.",
        extra: "El Hypsilophodon foxii del Cretácico temprano de Europa era un ornitópodo bípedo pequeño y ágil. Durante décadas los paleontólogos creyeron erróneamente que era arborícola. El éxito genético de InGen con esta especie fue notable: solo un 3% de los embriones no llegaron a término, en comparación con el 15-30% promedio del catálogo general. La especie se reprodujo naturalmente en Sorna, convirtiéndose en uno de los herbívoros menores más abundantes."
    },
    {
        name: "Liopleurodon",
        key: "LP-20487",
        family: "Pliosauridae",
        diet: "carnivoro",
        dietLabel: "CARNÍVORO",
        height: "3 m",
        length: "8 m",
        weight: "7,000 kg",
        location: "Isla Matanceros (marina)",
        emoji: "🐋",
        ingen: "Clonado en Isla Matanceros. Depredador marino de gran tamaño.",
        desc: "Clonado en Isla Matanceros. Depredador marino de gran tamaño y alta capacidad depredadora.",
        extra: "El Liopleurodon ferox del Jurásico tardío de Europa fue un pliosáurido de cuello corto con cuatro aletas poderosas y una mandíbula de hasta 3 metros. Aunque las estimaciones de tamaño fósil sugieren 5-7 m, los especímenes InGen alcanzaron longitudes de hasta 8 m gracias al tratamiento hormonal de crecimiento. Fue alojado en una instalación marina de aguas profundas en Matanceros. Es considerado el organismo más peligroso jamás clonado por InGen. Paradero actual: clasificado."
    },
    {
        name: "Maiasaura",
        key: "MI-14034",
        family: "Hadrosauridae",
        diet: "herbivoro",
        dietLabel: "HERBÍVORO",
        height: "2.4 m",
        length: "9 m",
        weight: "3,000 kg",
        location: "Isla Nublar",
        emoji: "🐄",
        ingen: "Llevada a Nublar para Fase 2. Comportamiento parental pronunciado.",
        desc: "Llevada a Nublar para Fase 2. Evidenció fuerte comportamiento parental.",
        extra: "La Maiasaura peeblesorum del Cretácico tardío de Norteamérica es famosa por ser el primer dinosaurio del que se evidenció cuidado parental extenso: los adultos regurgitaban alimento para las crías en el nido. Los especímenes InGen de Nublar establecieron colonias de anidación comunales en la zona este de la isla. El comportamiento defensivo colectivo ante amenazas a las crías fue documentado como extremadamente agresivo, con adultos cargando contra depredadores de mayor tamaño."
    },
    {
        name: "Mamenchisaurus",
        key: "BA-47919",
        family: "Mamenchisauridae",
        diet: "herbivoro",
        dietLabel: "HERBÍVORO",
        height: "11 m",
        length: "24 m",
        weight: "22,000 kg",
        location: "Isla Sorna",
        emoji: "🦕",
        ingen: "Clonado en Sorna. Traslado a Nublar cancelado por tamaño extremo.",
        desc: "Clonado en Sorna. Cancelado traslado a Nublar debido a limitaciones logísticas por su tamaño extremo.",
        extra: "El Mamenchisaurus sinocanadorum del Jurásico tardío asiático tenía el cuello más largo de todos los dinosaurios conocidos: entre 14 y 19 metros, representando hasta el 60% de su longitud total. InGen clonó tres ejemplares en Sorna, pero la logística de transporte (habría requerido barcos especiales con calados imposibles para el puerto de Nublar) hizo inviable el traslado. Los tres ejemplares fueron documentados consumiendo copas de árboles a alturas de hasta 11 metros."
    },
    {
        name: "Metriacanthosaurus",
        key: "MT-58036",
        family: "Metriacanthosauridae",
        diet: "carnivoro",
        dietLabel: "CARNÍVORO",
        height: "3 m",
        length: "8 m",
        weight: "Desconocido",
        location: "Isla Nublar",
        emoji: "🦖",
        ingen: "Llevado a Nublar para exhibición. Terópodo territorial.",
        desc: "Llevado a Nublar para exhibición. Terópodo de tamaño medio con comportamiento territorial.",
        extra: "El Metriacanthosaurus parkeri del Jurásico tardío de Europa es conocido por espinas neurales de altura media (de ahí su nombre: 'lagarto de espinas medias'). Era un depredador de tamaño medio situado entre los grandes (Allosaurus) y los pequeños (Dilophosaurus). Los ejemplares InGen de Nublar establecieron territorios claramente definidos y realizaban marcajes de bordes territoriales con arañazos en cortezas de árboles, comportamiento jamás predicho en los modelos conductuales."
    },
    {
        name: "Microceratus",
        key: "MC-87402",
        family: "Protoceratopsidae",
        diet: "herbivoro",
        dietLabel: "HERBÍVORO",
        height: "0.6 m",
        length: "1 m",
        weight: "15 kg",
        location: "Isla Sorna",
        emoji: "🐏",
        ingen: "Clonado en Sorna. Población aumentó exponencialmente.",
        desc: "Clonado en Sorna. Población aumentó exponencialmente por reproducción acelerada.",
        extra: "El Microceratus gobiensis del Cretácico tardío de Asia era uno de los ceratopsios más primitivos y pequeños. Sus ciclos reproductivos cortos y su dieta muy variada hicieron de esta especie la de más rápido crecimiento poblacional en Sorna. Estimaciones de 2001 indican que la población superaba los 2,000 individuos en la isla, convirtiéndola en la especie más numerosa per cápita después de Compsognathus. Funcionan como presas clave para múltiples depredadores."
    },
    {
        name: "Microraptor",
        key: "MR-45892",
        family: "Dromaeosauridae",
        diet: "carnivoro",
        dietLabel: "CARNÍVORO",
        height: "0.6 m",
        length: "1 m",
        weight: "5 kg",
        location: "Isla Matanceros",
        emoji: "🦅",
        ingen: "Clonado en Isla Matanceros. Plumaje funcional para planeo.",
        desc: "Clonado en Isla Matanceros. Presentó plumaje funcional para planeo.",
        extra: "El Microraptor gui del Cretácico temprano de China es uno de los dinosaurios no aviares más pequeños conocidos, con cuatro alas (plumas en brazos y patas). Podía planear eficientemente entre árboles. Los especímenes InGen exhibieron plumaje completo negro iridiscente, confirmando la hipótesis científica sobre coloración en microrraptores. Su capacidad de planeo documentada fue de hasta 40 metros horizontales desde alturas de 10 m. Se alimentaban principalmente de insectos, lagartijas y frutos."
    },
    {
        name: "Ornithocheirus",
        key: "OR-75981",
        family: "Ornithocheiridae",
        diet: "piscivoro",
        dietLabel: "PISCÍVORO",
        height: "2.5 m (bípedo)",
        length: "12 m",
        weight: "700 kg",
        location: "Isla Matanceros",
        emoji: "🦅",
        ingen: "Clonado en Isla Matanceros. Adaptado a vuelo de larga distancia.",
        desc: "Clonado en Isla Matanceros. Adaptado a vuelo de larga distancia.",
        extra: "El Ornithocheirus simus del Cretácico temprano de Europa era uno de los pterosaurios de mayor envergadura de su época, con estimaciones de hasta 12 metros. Tenía crestas en ambas mandíbulas que posiblemente servían para lectura hidrodinámica al pescar. Los especímenes InGen realizaron vuelos de hasta 800 km de distancia desde la isla (monitoreados por GPS subcutáneo), lo que confirma que la contención geográfica de las islas era completamente ineficiente para las especies voladoras. Escapó de las instalaciones."
    },
    {
        name: "Ornithomimus",
        key: "OM-67934",
        family: "Ornithomimidae",
        diet: "omnivoro",
        dietLabel: "OMNÍVORO",
        height: "2 m",
        length: "3.5 m",
        weight: "150 kg",
        location: "Isla Matanceros",
        emoji: "🏃",
        ingen: "Clonado en Isla Matanceros. Velocidad y comportamiento gregario.",
        desc: "Clonado en Isla Matanceros. Herbívoro/omnívoro veloz con comportamiento gregario.",
        extra: "El Ornithomimus edmontonicus del Cretácico tardío de Norteamérica era un ornitomimosáurido de pico sin dientes que consumía tanto plantas como pequeños animales. Estudios recientes de especímenes excepcionalmente preservados han revelado que los adultos tenían plumaje. Los especímenes InGen mostraron comportamiento de forrajeo altamente coordinado en grupos de 15-25 individuos, con individuos centinela que emitían llamadas de alarma mientras el grupo comía."
    },
    {
        name: "Pachycephalosaurus",
        key: "SA-76321",
        family: "Pachycephalosauridae",
        diet: "herbivoro",
        dietLabel: "HERBÍVORO",
        height: "2 m",
        length: "4.5 m",
        weight: "450 kg",
        location: "Isla Nublar / Isla Sorna",
        emoji: "💀",
        ingen: "Llevado a Nublar para Fase 2. Población en Sorna aumentó considerablemente.",
        desc: "Llevado a Nublar para Fase 2. En Sorna la población aumentó considerablemente.",
        extra: "El Pachycephalosaurus wyomingensis del Cretácico tardío de Norteamérica tenía una cúpula craneal de hueso sólido de hasta 25 cm de grosor. Los combates de cabezazos entre machos podían generar fuerzas de impacto equivalentes a un coche chocando a 30 km/h. Los especímenes InGen de Sorna desarrollaron jerarquías de dominancia estables en grupos de 8-12 individuos, con temporadas de celo claramente marcadas que generaban niveles de violencia intraespecífica significativos."
    },
    {
        name: "Pachyrhinosaurus",
        key: "PC-50892",
        family: "Ceratopsidae",
        diet: "herbivoro",
        dietLabel: "HERBÍVORO",
        height: "2.5 m",
        length: "6 m",
        weight: "4,000 kg",
        location: "Isla Sorna",
        emoji: "🦛",
        ingen: "Clonado en la última fase en Sorna. Registros oficiales ocultos.",
        desc: "Clonado en la última fase en Sorna. Registros oficiales fueron ocultos.",
        extra: "El Pachyrhinosaurus canadensis del Cretácico tardío de Norteamérica tenía una protuberancia ósea rugosa (boss) en lugar de cuernos nasales, con cuernos parietales variables. Fue uno de los últimos especímenes clonados antes del cierre de Re-Genesis, razón por la que InGen eliminó deliberadamente sus registros de los servidores principales para que no fueran confiscados por la Guardia Genética. Solo fragmentos de los datos de secuencia genética sobreviven en servidores de respaldo recuperados."
    },
    {
        name: "Parasaurolophus",
        key: "CS-62085",
        family: "Hadrosauridae",
        diet: "herbivoro",
        dietLabel: "HERBÍVORO",
        height: "3 m",
        length: "7.5 m",
        weight: "2,500 kg",
        location: "Isla Nublar / Isla Sorna / Isla Matanceros",
        emoji: "🎺",
        ingen: "Presente en múltiples islas. Comunicación acústica avanzada.",
        desc: "Presente en Nublar, Sorna y Matanceros. Comunicación acústica avanzada.",
        extra: "El Parasaurolophus walkeri del Cretácico tardío de Norteamérica tenía una cresta tubular hueca que funcionaba como instrumento de viento. Los estudios acústicos de los especímenes InGen revelaron que la cresta produce ondas de presión de baja frecuencia (30-80 Hz) que se propagan eficientemente a través de la densa vegetación tropical, con un alcance comunicacional efectivo de hasta 10 km. Poblaciones en diferentes islas desarrollaron dialectos acústicos distintos en menos de una generación."
    },
    {
        name: "Plateosaurus",
        key: "PL-47291",
        family: "Plateosauridae",
        diet: "herbivoro",
        dietLabel: "HERBÍVORO",
        height: "2 m",
        length: "7.5 m",
        weight: "3,500 kg",
        location: "Isla Matanceros",
        emoji: "🦕",
        ingen: "Gran dinosaurio prosarópodo clonado exclusivamente en Isla Matanceros. Los ejemplares adultos representan un riesgo moderado de daño estructural si se sienten amenazados.",
        desc: "Gran dinosaurio prosarópodo herbívoro clonado exclusivamente en la Isla Matanceros. Se desplaza tanto de forma bípeda como cuadrúpeda y habita principalmente en zonas boscosas y llanuras con vegetación abundante. Su largo cuello le permite acceder a follaje alto, complementando el nicho ecológico de otros herbívoros más pequeños presentes en la isla.",
        extra: "Plateosaurus trossingensis es uno de los primeros grandes dinosaurios herbívoros, perteneciente al grupo de los sauropodomorfos basales. Se caracteriza por un cuello largo y flexible, una cabeza pequeña con dientes serrados en forma de hoja adaptados para triturar vegetación, y extremidades robustas que le permitian moverse en dos o cuatro patas. Mostraba una notable plasticidad de crecimiento: los individuos adultos variaban considerablemente en tamaño."
    },
    {
        name: "Plesiosaurus",
        key: "PL-54732",
        family: "Plesiosauridae",
        diet: "piscivoro",
        dietLabel: "PISCÍVORO",
        height: "1.5 m",
        length: "11 m",
        weight: "3,500 kg",
        location: "Isla Nublar",
        emoji: "🐍",
        ingen: "Llevado a Nublar para Fase 2. Adaptado a entorno marino controlado.",
        desc: "Llevado a Nublar para Fase 2. Adaptado a entorno marino controlado.",
        extra: "El Plesiosaurus dolichodeirus del Jurásico temprano fue un plesiosauroideo de cuello largo, cuatro aletas y mandíbulas llenas de dientes cónicos para cazar peces. InGen diseñó una laguna marina de agua controlada en la zona sur de Nublar para albergar sus especímenes acuáticos. El ejemplar de Plesiosaurus fue uno de los más difíciles de clonar por la escasez de ADN útil recuperado. Las modificaciones genéticas incluyeron ADN de tortuga laúd para la termorregulación."
    },
    {
        name: "Proceratosaurus",
        key: "PR-10045",
        family: "Proceratosauridae",
        diet: "carnivoro",
        dietLabel: "CARNÍVORO",
        height: "1.5 m",
        length: "3 m",
        weight: "80 kg",
        location: "Isla Nublar",
        emoji: "🦖",
        ingen: "Llevado a Nublar. Base genética para estudios tiranosauroideos.",
        desc: "Llevado a Nublar. Base genética para estudios tiranosauroideos.",
        extra: "El Proceratosaurus bradleyi del Jurásico tardío de Gran Bretaña es considerado uno de los tiranosauroides más primitivos conocidos, lo que ayuda a trazar los orígenes evolutivos del T. rex. InGen lo incluyó en el catálogo no para exhibición pública sino como organismo de referencia para sus estudios de reconstrucción genética de tiranosáuridos. Los datos genéticos obtenidos de este espécimen se usaron como 'esqueleto' para rellenar lagunas en el genoma del Tyrannosaurus rex."
    },
    {
        name: "Pteranodon",
        key: "MK-77616",
        family: "Pteranodontidae",
        diet: "piscivoro",
        dietLabel: "PISCÍVORO",
        height: "2.2 m",
        length: "10 m (env.)",
        weight: "500 kg",
        location: "Isla Sorna",
        emoji: "🦅",
        ingen: "Clonado ilegalmente durante Re-Genesis. Vuelo de largo alcance.",
        desc: "Clonado ilegalmente durante Re-Genesis. Capacidad de vuelo de largo alcance.",
        extra: "El Pteranodon longiceps del Cretácico tardío de Norteamérica es el pterosaurio más icónico. No tenía dientes y pescaba al vuelo como un pelícano moderno. InGen los clonó durante Re-Genesis sin autorizaciones, razón por la que fueron parte del decomiso de la Guardia Genética. Sin embargo, múltiples ejemplares ya estaban en libertad en Sorna. Estos individuos establecieron colonias en los acantilados de la isla y comenzaron a mostrar comportamiento agresivo hacia humanos, especialmente en defensa de nidos."
    },
    {
        name: "Quetzalcoatlus",
        key: "QT-92356",
        family: "Azhdarchidae",
        diet: "carnivoro",
        dietLabel: "CARNÍVORO",
        height: "3.5 m",
        length: "15 m (env.)",
        weight: "800 kg",
        location: "Isla Matanceros",
        emoji: "🦅",
        ingen: "Clonado en Isla Matanceros. Envergadura superior a 10 metros.",
        desc: "Clonado en Isla Matanceros. Envergadura superior a 10 metros.",
        extra: "El Quetzalcoatlus northropi del Cretácico tardío de Norteamérica fue el animal volador más grande conocido, con una envergadura estimada de 10-11 metros y una altura de jirafa cuando caminaba en cuatro patas. Se alimentaba principalmente de vertebrados terrestres que capturaría caminando y punteando el suelo como una garza gigante. Los especímenes InGen podían transportar presas de hasta 80 kg. InGen los consideró para uso militar en el Proyecto Thanatos, cuya documentación permanece clasificada."
    }
];
