// SPECIES DATA PART 3 — S through V (final)
var SPECIES_PART3 = [
    {
        name: "Scutosaurus",
        key: "SC-78134",
        family: "Pareiasauridae",
        diet: "herbivoro",
        dietLabel: "HERBÍVORO",
        height: "1.5 m",
        length: "3 m",
        weight: "1,200 kg",
        location: "Isla Matanceros",
        emoji: "🛡️",
        ingen: "Clonado en Isla Matanceros. Herbívoro acorazado del Pérmico.",
        desc: "Clonado en Isla Matanceros. Herbívoro acorazado del Pérmico.",
        extra: "El Scutosaurus karpinskii del Pérmico tardío de Rusia era un pareiasáurido: un reptil acorazado de cuatro patas, con la piel repleta de osteodermos. Pesaba entre 700-900 kg y era el equivalente del hipopótamo en su ecosistema pérmico. InGen lo clonó como parte del subproyecto de fauna paleozoica junto al Dimetrodon y el Gorgonopsid. La convivencia de estas tres especies en el mismo espacio recreó dinámicas predador-presa del Pérmico que no se habían observado en más de 250 millones de años."
    },
    {
        name: "Segisaurus",
        key: "SG-93049",
        family: "Coelophysidae",
        diet: "carnivoro",
        dietLabel: "CARNÍVORO",
        height: "0.5 m",
        length: "1 m",
        weight: "4 kg",
        location: "Isla Nublar",
        emoji: "🦎",
        ingen: "Llevado a Nublar. Pequeño terópodo ágil.",
        desc: "Llevado a Nublar. Pequeño terópodo ágil.",
        extra: "El Segisaurus halli del Jurásico temprano de Arizona es uno de los coelofísidos más pequeños conocidos. Era ágil y rápido, con huesos huecos (como las aves modernas). InGen lo incluyó en el catálogo de Nublar principalmente por su valor científico: es uno de los dinosaurios más primitivos y completos del Jurásico temprano norteamericano. Los especímenes vivían en grietas y zonas arbustivas densas, haciéndolos difíciles de monitorear. Probablemente sobrevivió al incidente de 1993 por su pequeño tamaño y agilidad."
    },
    {
        name: "Spinosaurus",
        key: "SP-61928",
        family: "Spinosauridae",
        diet: "piscivoro",
        dietLabel: "PISCÍVORO",
        height: "5.5 m",
        length: "15 m",
        weight: "8,000 kg",
        location: "Isla Sorna",
        emoji: "⚠️",
        ingen: "CLONACIÓN ILEGAL — Amalgama con ADN de Suchomimus, Baryonyx y cocodrilo del Nilo.",
        desc: "Clonado ilegalmente en Re-Genesis. Amalgama con ADN de Suchomimus, Baryonyx y cocodrilo del Nilo. Capacidad pulmonar y fuerza mandibular superiores.",
        extra: "El Espécimen InGen de Spinosaurus fue el organismo más grande jamás clonado ilegalmente por la corporación. No es una clonación pura de Spinosaurus aegyptiacus: es una amalgama que incorpora secuencias de Spinosaurus, Suchomimus, Baryonyx, cocodrilo del Nilo y presuntamente material genético de avemano aún no identificado. Sus capacidades superan a cualquier registro fósil: cuatripedia opcional, natación activa a 15 nudos, apnea de hasta 8 minutos. Fue responsable de múltiples muertes en el incidente de 2001. Clasificado como Amenaza Nivel Omega."
    },
    {
        name: "Stegosaurus",
        key: "SG-24492",
        family: "Stegosauridae",
        diet: "herbivoro",
        dietLabel: "HERBÍVORO",
        height: "4 m",
        length: "9 m",
        weight: "2,500 kg",
        location: "Isla Nublar / Isla Sorna / Isla Matanceros",
        emoji: "♦️",
        ingen: "Presente en múltiples islas. Placas dorsales con alta vascularización.",
        desc: "Presente en Nublar, Sorna y Matanceros. Placas dorsales con alta vascularización.",
        extra: "El Stegosaurus ungulatus del Jurásico tardío de Norteamérica es uno de los dinosaurios más reconocibles por las placas dorsales alternadas y las cuatro púas de la cola (thagomizer). Las placas están altamente vascularizadas y cambian de coloración al enrojecerse con sangre durante estados de excitación o regulación térmica. Los especímenes InGen de Sorna son los individuos de mayor tamaño documentados, alcanzando 9.5 m de longitud. Se reprodujeron exitosamente, con al menos seis generaciones documentadas."
    },
    {
        name: "Stygimoloch",
        key: "ST-29513",
        family: "Pachycephalosauridae",
        diet: "herbivoro",
        dietLabel: "HERBÍVORO",
        height: "2 m",
        length: "3 m",
        weight: "450 kg",
        location: "Isla Sorna",
        emoji: "💀",
        ingen: "Clonado en Sorna de forma inesperada. Confirmado como especie distinta.",
        desc: "Clonado en Sorna de forma inesperada. Confirmado como especie distinta.",
        extra: "El Stygimoloch spinifer del Cretácico tardío de Norteamérica tiene una de las morfologías craneales más llamativas: una domo craneal rodeado de espinas tabulares y cuernos gruesos. Algunos paleontólogos lo consideran una forma juvenil de Pachycephalosaurus, pero los especímenes InGen demostraron ser una especie genéticamente distinta. Su aparición en Sorna fue inesperada, posiblemente resultado de una contaminación cruzada de muestras genéticas en el laboratorio principal. Comportamiento explícitamente agresivo con humanos."
    },
    {
        name: "Styracosaurus",
        key: "SR-94053",
        family: "Ceratopsidae",
        diet: "herbivoro",
        dietLabel: "HERBÍVORO",
        height: "1.8 m",
        length: "5.5 m",
        weight: "3,000 kg",
        location: "Isla Nublar",
        emoji: "🦛",
        ingen: "Llevado a Nublar para Fase 2. Cornamenta para combate ritual.",
        desc: "Llevado a Nublar para Fase 2. Cornamenta desarrollada para combate ritual.",
        extra: "El Styracosaurus albertensis del Cretácico tardío de Norteamérica tenía un espectacular collar óseo con seis largos cuernos parietales y un largo cuerno nasal central. Su función era principalmente exhibicional y para combate intraespecífico. Los especímenes InGen mostraron torneos de combate ritualizados entre machos durante períodos reproductivos, con enfrentamientos que podían durar hasta cuatro horas sin resultar en heridas fatales entre competidores, sugiriendo un sistema de resolución de dominancia evolutivamente refinado."
    },
    {
        name: "Suchomimus",
        key: "SM-84752",
        family: "Spinosauridae",
        diet: "piscivoro",
        dietLabel: "PISCÍVORO",
        height: "4 m",
        length: "11 m",
        weight: "3,000 kg",
        location: "Isla Nublar / Isla Matanceros",
        emoji: "🐊",
        ingen: "Un ejemplar confundido con Baryonyx. Trasladado posteriormente a Matanceros.",
        desc: "Un ejemplar llevado a Nublar fue confundido con Baryonyx. Posteriormente trasladado a Matanceros.",
        extra: "El Suchomimus tenerensis del Cretácico temprano de África era un espinosáurido piscívoro con un largo morro crocodyliforme y garras curvadas en los pulgares. Su confusión con Baryonyx por el personal de campo de InGen fue un error significativo que evidenció los problemas de control de calidad en el programa de clonación. Cuando fue reclasificado correctamente, ya había convivido varios meses con el Baryonyx de Nublar, desarrollando una relación de tolerancia mutua que sorprendió a los etólogos."
    },
    {
        name: "Tanystropheus",
        key: "TN-50734",
        family: "Tanystropheidae",
        diet: "piscivoro",
        dietLabel: "PISCÍVORO",
        height: "1 m",
        length: "6 m",
        weight: "600 kg",
        location: "Isla Matanceros",
        emoji: "🐍",
        ingen: "Clonado en Isla Matanceros. Reptil de cuello extremadamente largo.",
        desc: "Clonado en Isla Matanceros. Reptil de cuello extremadamente largo.",
        extra: "El Tanystropheus hydroides del Triásico medio de Europa es uno de los reptiles más extraños conocidos, con un cuello de hasta 3 metros de longitud soportado por solo 12 vértebras extremadamente elongadas. Estudios recientes sugieren que era semiacuático y piscívoro. InGen tuvo dificultades extremas para clonar exitosamente esta especie: la estructura genética es muy divergente de cualquier reptil moderno. Solo dos especímenes viables fueron producidos, ambos en Matanceros, donde permanecieron en la zona costera de la instalación."
    },
    {
        name: "Tapejara",
        key: "TP-87421",
        family: "Tapejaridae",
        diet: "omnivoro",
        dietLabel: "OMNÍVORO",
        height: "1.5 m (bípedo)",
        length: "4 m (env.)",
        weight: "200 kg",
        location: "Isla Matanceros",
        emoji: "🦜",
        ingen: "Clonado en Isla Matanceros. Crestado y adaptado a vuelo maniobrable.",
        desc: "Clonado en Isla Matanceros. Crestado y adaptado a vuelo maniobrable.",
        extra: "El Tapejara wellnhoferi del Cretácico temprano de Brasil tiene una de las crestas más vistosas de todos los pterosaurios: una estructura triangular ósea cubierta de una membrana vascularizada brillante. Su dieta era probablemente omnívora (frutas, peces, invertebrados). InGen lo admiró tanto estéticamente que fue incluido en el catálogo de Fase 2 de Nublar, aunque el incidente de 1993 lo impidió. Los especímenes de Matanceros demostraron inteligencia superior a otros pterosaurios: aprendieron a abrir contenedores de alimento con cerrojo simple."
    },
    {
        name: "Therizinosaurus",
        key: "TZ-56389",
        family: "Therizinosauridae",
        diet: "herbivoro",
        dietLabel: "HERBÍVORO",
        height: "5 m",
        length: "10 m",
        weight: "6,000 kg",
        location: "Isla Matanceros",
        emoji: "🌿",
        ingen: "Clonado en Isla Matanceros. Garras de gran longitud con comportamiento defensivo extremo.",
        desc: "Clonado en Isla Matanceros. Garras de gran longitud con comportamiento defensivo extremo.",
        extra: "El Therizinosaurus cheloniformis del Cretácico tardío de Asia tenía las garras más largas de cualquier animal conocido: hasta 1 metro de longitud cada una. Paradójicamente, era herbívoro, usando las garras para atraer ramas hacia su boca. Los especímenes InGen mostraron que en respuesta a amenazas percibidas, la reacción defensiva involucra barrer con las garras en arco, generando fuerzas suficientes para deformar estructuras de acero de 6 mm de grosor. Dos operativos resultaron gravemente heridos en Matanceros al infravalorar su radio de peligro."
    },
    {
        name: "Torosaurus",
        key: "TR-39217",
        family: "Ceratopsidae",
        diet: "herbivoro",
        dietLabel: "HERBÍVORO",
        height: "3 m",
        length: "7.5 m",
        weight: "5,000 kg",
        location: "Isla Matanceros",
        emoji: "🦕",
        ingen: "Clonado en Isla Matanceros. Posible relación filogenética cercana a Triceratops.",
        desc: "Clonado en Isla Matanceros. Posible relación filogenética cercana a Triceratops.",
        extra: "El Torosaurus latus del Cretácico tardío de Norteamérica tenía el cráneo más grande de cualquier animal terrestre conocido, superando los 2.6 metros de longitud. Algunos paleontólogos consideran que es en realidad un Triceratops maduro. El análisis genético de los especímenes InGen reveló diferencias suficientes para justificar su clonación como especie separada. La convivencia en Matanceros con ejemplares de Triceratops resultó pacífica, con ambas especies formando grupos mixtos de alimentación y defensa mutua ante depredadores."
    },
    {
        name: "Triceratops",
        key: "TK-21268",
        family: "Ceratopsidae",
        diet: "herbivoro",
        dietLabel: "HERBÍVORO",
        height: "3.2 a 3.6 m",
        length: "9 m",
        weight: "6,000 kg",
        location: "Isla Nublar / Isla Sorna / Isla Matanceros",
        emoji: "🦕",
        ingen: "Múltiples ejemplares clonados. Reproducción exitosa en cautiverio.",
        desc: "Múltiples ejemplares clonados. Tres trasladados a Nublar y al menos ocho permanecieron en Sorna. Algunos fueron llevados a Matanceros. Reproducción exitosa en cautiverio.",
        extra: "El Triceratops horridus del Cretácico tardío de Norteamérica es el ceratópsido más conocido. Sus tres cuernos y collar óseo eran usados tanto para defensa como para combate intraespecífico. Fue la primera especie en la que InGen documentó reproducción espontánea exitosa en semicautiverio (en Sorna). Las crías nacen sin cuernos desarrollados y permanecen bajo protección del grupo durante sus primeros 3 meses. Los adultos forman círculos defensivos ante amenazas, con crías en el centro, comportamiento idéntico al de bisontes modernos."
    },
    {
        name: "Troodon",
        key: "TR-11060",
        family: "Troodontidae",
        diet: "omnivoro",
        dietLabel: "OMNÍVORO",
        height: "1 m",
        length: "2.4 m",
        weight: "50 kg",
        location: "Isla Nublar",
        emoji: "🧠",
        ingen: "John Hammond ordenó sacrificarlos por inestabilidad conductual e inteligencia avanzada.",
        desc: "Varios ejemplares clonados y llevados a Nublar. John Hammond ordenó sacrificarlos por inestabilidad conductual e inteligencia avanzada.",
        extra: "El Troodon formosus del Cretácico tardío de Norteamérica tenía el coeficiente encéfalo-cuerpo más alto de todos los dinosaurios no aviares conocidos, sugiriendo inteligencia avanzada. Los especímenes InGen superaron todas las pruebas de resolución de problemas diseñadas para ellos, aprendieron a manipular pestillos y cerrojos en menos de 6 horas de exposición, y mostraron comportamientos de engaño deliberado ante los supervisores humanos. Hammond ordenó su eliminación cuando uno de los especímenes demostró capacidad de imitación vocal básica. El proceso de sacrificio estuvo a punto de fracasar."
    },
    {
        name: "Tylosaurus",
        key: "TY-79201",
        family: "Mosasauridae",
        diet: "carnivoro",
        dietLabel: "CARNÍVORO",
        height: "1.8 m (lomo)",
        length: "14 m",
        weight: "10,000 kg",
        location: "Isla Nublar",
        emoji: "🐋",
        ingen: "Un ejemplar clonado y llevado discretamente a Nublar para Fase 2.",
        desc: "Un ejemplar clonado y llevado discretamente a Nublar para Fase 2.",
        extra: "El Tylosaurus proriger del Cretácico tardío de Norteamérica era uno de los mosasaurios más grandes conocidos, un reptil marino que dominaba los mares del interior de Norteamérica. Se alimentaba de peces, tiburones, aves marinas y otros mosasaurios. InGen alojó el único ejemplar clonado en la laguna marina de Nublar destinada a la Fase 2 del parque. La instalación fue diseñada específicamente para espectáculos de alimentación. El ejemplar sobrevivió al incidente de 1993 y su estado actual es desconocido aunque se han reportado avistamientos anómalos en aguas del Pacífico."
    },
    {
        name: "Tyrannosaurus Rex",
        key: "RD-12376",
        family: "Tyrannosauridae",
        diet: "carnivoro",
        dietLabel: "CARNÍVORO",
        height: "5.2 m",
        length: "13.5 m",
        weight: "3,000 kg",
        location: "Isla Nublar / Isla Sorna / Isla Matanceros",
        emoji: "👑",
        ingen: "Siete ejemplares clonados. El más icónico y peligroso del catálogo.",
        desc: "Siete ejemplares clonados. Uno en Nublar, los demás en Sorna. Uno fue trasladado posteriormente a Matanceros.",
        extra: "El Tyrannosaurus rex del Cretácico tardío de Norteamérica es el depredador terrestre más icónico. InGen invirtió más recursos en su clonación que en cualquier otra especie: el ADN fue el más difícil de recuperar y requirió 39% de relleno genético de aves modernas. Los siete ejemplares clonados presentaron variaciones de hasta 15% en tamaño, indicando inestabilidad de expresión genética. El ejemplar de Nublar es el más famoso: sobreviviente del incidente de 1993, fue trasladado a San Diego en 1997 y posteriormente a Matanceros. Los ejemplares de Sorna son más grandes y agresivos que el de Nublar."
    },
    {
        name: "Ultimate Predator (Híbrido)",
        key: "UP-00001",
        family: "[CLASIFICADO]",
        diet: "clasificado",
        dietLabel: "CLASIFICADO",
        height: "[CLASIFICADO]",
        length: "[CLASIFICADO]",
        weight: "[CLASIFICADO]",
        location: "[CLASIFICADO]",
        emoji: "☠️",
        ingen: "INFORMACIÓN TOTALMENTE RESTRINGIDA — Amenaza Nivel Omega",
        desc: "Entidad clasificada. Posible híbrido experimental de aplicaciones militares avanzadas. Información restringida.",
        extra: "La información sobre esta entidad está clasificada con nivel de acceso OMEGA. Lo que se sabe proviene exclusivamente de testimonios de sobrevivientes: el organismo presenta capacidades físicas que exceden a cualquier depredador natural o clonado previamente documentado. Evidencias circunstanciales sugieren incorporación de material genético de múltiples depredadores ápice, incluyendo posiblemente calamar gigante, orca y material no identificado. Cualquier personal que haya tenido contacto visual con el espécimen ha sido reubicado bajo acuerdos de confidencialidad de por vida. Esta ficha podría ser eliminada en cualquier momento."
    },
    {
        name: "Utahraptor",
        key: "UR-21345",
        family: "Dromaeosauridae",
        diet: "carnivoro",
        dietLabel: "CARNÍVORO",
        height: "2.5 m",
        length: "7 m",
        weight: "1,000 kg",
        location: "Isla Matanceros",
        emoji: "⚔️",
        ingen: "Cinco ejemplares clonados en Isla Matanceros para uso militar. Imitación vocal humana.",
        desc: "Cinco ejemplares clonados en Isla Matanceros para uso militar. Inteligencia avanzada y capacidad de imitación vocal humana.",
        extra: "El Utahraptor ostrommaysorum del Cretácico temprano de Utah era el dromeosáurido más grande conocido, con garras de hasta 24 cm. InGen lo clonó específicamente bajo solicitud de un cliente militar no identificado (designado en los archivos como 'Proyecto New Era'). Los cinco ejemplares mostraron una capacidad de aprendizaje que superó incluso al Troodon en pruebas de resolución de problemas. La imitación vocal humana —capacidad no documentada en ningún dinosaurio— fue descubierta accidentalmente cuando uno de ellos reprodujo el nombre del supervisor de laboratorio. Los registros de audio fueron clasificados."
    },
    {
        name: "Velociraptor",
        key: "DV-70189",
        family: "Dromaeosauridae",
        diet: "carnivoro",
        dietLabel: "CARNÍVORO",
        height: "1.8 m",
        length: "3.9 m",
        weight: "226 kg",
        location: "Isla Nublar / Isla Sorna / Isla Matanceros",
        emoji: "⚡",
        ingen: "La especie más peligrosa del catálogo. Múltiples variantes y cepas clonadas.",
        desc: "Múltiples variantes clonadas. Primeros lotes llevados a Nublar. En Sorna la especie se reprodujo masivamente tras el incidente de 1993 y el huracán Clarissa. Nueva cepa creada en Re-Genesis con mayor agresividad y coordinación, trasladada a Matanceros para el Proyecto Chaos.",
        extra: "El Velociraptor mongoliensis del Cretácico tardío asiático era en realidad del tamaño de un pavo, con plumaje completo. Los especímenes InGen son morfológicamente más cercanos a Deinonychus, aunque InGen insistió en llamarlos Velociraptor. Presentan plumaje vestigial. Desarrollaron sistemas de comunicación táctica equivalentes a las estrategias de caza de lobos grises. La cepa de Matanceros (Re-Genesis) presenta un coeficiente de agresión 340% superior a la cepa original, con comportamientos de caza prolongada de hasta 72 horas continuas. Han demostrado capacidad de usar herramientas rudimentarias. Son considerados por múltiples consultores como el mayor riesgo de seguridad biótica del planeta."
    }
];
