// SPECIES DATA PART 1 — A through G
var SPECIES_PART1 = [
    {
        name: "Acrocanthosaurus",
        key: "AC-41985",
        family: "Carcharodontosauridae",
        diet: "carnivoro",
        dietLabel: "CARNÍVORO",
        height: "4 m",
        length: "12 m",
        weight: "6,000 kg",
        location: "Isla Nublar (secreto)",
        emoji: "🦖",
        ingen: "Clonado en secreto como parte de un subproyecto experimental. Solo un ejemplar viable fue producido.",
        desc: "Antes del huracán Clarissa, su clonación se mantuvo en secreto como parte de un subproyecto experimental. Solo se logró clonar un ejemplar viable. Presentaba hipertrofia en las espinas neurales dorsales con posible función termorreguladora y de exhibición. Su metabolismo era elevado y mostró comportamiento altamente territorial. Su paradero posterior al huracán permanece clasificado.",
        extra: "El Acrocanthosaurus atokensis fue un carnosaurio del Cretácico inferior norteamericano. Su característica más notable eran las largas espinas neurales vertebrales que formaban una cresta o joroba muscular a lo largo del dorso. InGen incorporó genes modernos de ave para estabilizar el ADN degenerado. Los registros de seguimiento de este espécimen fueron borrados del servidor central en 1995."
    },
    {
        name: "Albertosaurus",
        key: "AB-51239",
        family: "Tyrannosauridae",
        diet: "carnivoro",
        dietLabel: "CARNÍVORO",
        height: "3.5 m",
        length: "9 m",
        weight: "2,000 kg",
        location: "Isla Matanceros",
        emoji: "🦖",
        ingen: "Tres ejemplares clonados para estudio comparativo con Tyrannosaurus rex.",
        desc: "Tres ejemplares fueron clonados en la Isla Matanceros. Se estudió su comportamiento social comparativo con Tyrannosaurus rex. Mostraron mayor agilidad y resistencia, con posible caza cooperativa en etapas juveniles.",
        extra: "El Albertosaurus sarcophagus era un tiranosáurido del Cretácico tardío de Norteamérica. A diferencia de su primo T. rex, era más ágil y esbelto. Los tres ejemplares clonados por InGen demostraron comportamientos de caza en dúo no documentados en el registro fósil, lo que sugiere que el ADN de relleno utilizado provino de aves de caza coordinada. Actualmente en paradero desconocido."
    },
    {
        name: "Allosaurus",
        key: "AL-98234",
        family: "Allosauridae",
        diet: "carnivoro",
        dietLabel: "CARNÍVORO",
        height: "3.8 m",
        length: "9.5 m",
        weight: "2,500 kg",
        location: "Isla Sorna",
        emoji: "🦖",
        ingen: "Datos eliminados por el Proyecto Agreus debido a inestabilidad genética.",
        desc: "Dos ejemplares fueron clonados en Isla Sorna antes del huracán Clarissa. Posteriormente, los datos fueron eliminados por el Proyecto Agreus debido a inestabilidad genética en regeneración ósea. Mostraron gran agresividad y amplio rango mandibular.",
        extra: "El Allosaurus fragilis, apodado el 'depredador del Jurásico', tenía maxilares que podía abrir casi 90°, utilizando la cabeza como hacha contra sus presas. Los ejemplares InGen presentaron una rara condición de regeneración ósea acelerada que causó deformidades craneales progresivas, razón por la que el Proyecto Agreus ordenó la eliminación de todos los registros y, presuntamente, de los especímenes mismos."
    },
    {
        name: "Amargasaurus",
        key: "AM-30271",
        family: "Dicraeosauridae",
        diet: "herbivoro",
        dietLabel: "HERBÍVORO",
        height: "3 m",
        length: "10 m",
        weight: "2,000 kg",
        location: "Isla Matanceros",
        emoji: "🌿",
        ingen: "Clonado para el Proyecto Chaos. Espinas cervicales reforzadas con tejido queratinizado inducido.",
        desc: "InGen logró clonar esta especie para el Proyecto Chaos en Isla Matanceros. Las espinas cervicales fueron reforzadas con tejido queratinizado inducido, posiblemente con función defensiva y de regulación térmica.",
        extra: "El Amargasaurus cazaui es un saurópodo del Cretácico inferior sudamericano, famoso por sus dos filas de espinas cervicales altas y paralelas. Los científicos debaten si estas espinas sostenían una vela de piel o eran estructuras libres. En los especímenes de InGen, la modificación genética con queratina adicional las convirtió en estructuras más resistentes, posiblemente para defensa activa."
    },
    {
        name: "Ankylosaurus",
        key: "AK-66781",
        family: "Ankylosauridae",
        diet: "herbivoro",
        dietLabel: "HERBÍVORO",
        height: "2 m",
        length: "8 m",
        weight: "6,000 kg",
        location: "Isla Sorna / Matanceros",
        emoji: "🛡️",
        ingen: "Clonado durante Operación Re-Genesis. Armadura con mayor densidad mineral que el registro fósil.",
        desc: "Clonado durante la operación Re-Genesis. Su armadura ósea presentó mayor densidad mineral que registros fósiles, producto de sobreexpresión genética de calcificación. Comportamiento principalmente defensivo y gregario.",
        extra: "El Ankylosaurus magniventris fue uno de los dinosaurios acorazados más grandes conocidos, con placas óseas (osteodermos) incrustadas en la piel y una maza caudal capaz de romper huesos. Los ejemplares InGen presentaron una densidad ósea aproximadamente un 34% superior al máximo registrado en fósiles, lo que los hacía prácticamente invulnerables a ataques frontales de otros especímenes."
    },
    {
        name: "Baryonyx",
        key: "BY-56214",
        family: "Spinosauridae",
        diet: "piscivoro",
        dietLabel: "PISCÍVORO",
        height: "3 m",
        length: "10 m",
        weight: "1,200 kg",
        location: "Isla Nublar / Isla Sorna",
        emoji: "🐊",
        ingen: "Llevado a Isla Nublar para la Fase 2 del parque. Adaptado con mejoras metabólicas piscívoras.",
        desc: "Llevado a Isla Nublar para exhibición en la Fase 2 del parque. Algunos ejemplares permanecieron en Sorna. Adaptado con mejoras metabólicas para hábitos semiacuáticos.",
        extra: "El Baryonyx walkeri del Cretácico inferior de Europa era un espinosáurido especializado en pesca. Sus garras delanteras de 30 cm eran ideales para atrapar peces. InGen introdujo modificaciones metabólicas basadas en ADN de cocodrilo americano para mejorar la capacidad de apnea y la eficiencia digestiva con proteínas animales acuáticas. Un ejemplar fue confundido con Suchomimus por personal de campo."
    },
    {
        name: "Brachiosaurus",
        key: "JD-91173",
        family: "Brachiosauridae",
        diet: "herbivoro",
        dietLabel: "HERBÍVORO",
        height: "12.4 m",
        length: "21 m",
        weight: "30,000 kg",
        location: "Isla Nublar / Isla Sorna / Isla Matanceros",
        emoji: "🦕",
        ingen: "Parte fundamental de la fauna de Jurassic Park. Crecimiento acelerado hormonalmente.",
        desc: "Parte fundamental de la fauna de Jurassic Park en Nublar. Algunos ejemplares permanecieron en Sorna y otros fueron trasladados a Isla Matanceros. Presentaron crecimiento acelerado inducido hormonalmente.",
        extra: "El Brachiosaurus altithorax del Jurásico tardío norteamericano es uno de los dinosaurios más icónicos por su cuello extremadamente largo. Los especímenes de InGen recibieron tratamiento hormonal de crecimiento IGF-1 modificado, lo que redujo el período hasta madurez de estimados 20-30 años naturales a aproximadamente 6-8 años. El ejemplar original de Nublar fue el primer dinosaurio avistado por los visitantes en 1993."
    },
    {
        name: "Carnotaurus",
        key: "CR-41062",
        family: "Abelisauridae",
        diet: "carnivoro",
        dietLabel: "CARNÍVORO",
        height: "3 m",
        length: "10.5 m",
        weight: "1,500 kg",
        location: "Isla Nublar / Isla Sorna / Isla Matanceros",
        emoji: "🦖",
        ingen: "Ejemplares en Sorna desarrollaron capacidad limitada de cambio de color dérmico.",
        desc: "Llevado a Nublar para Fase 2. Ejemplares en Sorna desarrollaron capacidad limitada de cambio de color dérmico mediante incorporación de cromatóforos derivados de ADN moderno. El ejemplar de Nublar fue trasladado a Matanceros.",
        extra: "El Carnotaurus sastrei del Cretácico tardío sudamericano es famoso por sus cuernos sobre los ojos y su piel con grandes protuberancias dérmicas. InGen incorporó genes de cromatóforos de Camaleón en el genoma de los ejemplares de Sorna, resultando en una capacidad de camuflaje parcial especialmente efectiva contra el movimiento: al permanecer estáticos, los especímenes eran prácticamente invisibles a distancias superiores a 15 metros."
    },
    {
        name: "Cearadactylus",
        key: "INGEN-CEA-010",
        family: "Cearadactylidae",
        diet: "piscivoro",
        dietLabel: "PISCÍVORO",
        height: "n/a",
        length: "4.5 m (env.)",
        weight: "25 kg",
        location: "Isla Nublar",
        emoji: "🦅",
        ingen: "Llevado a Isla Nublar para Fase 2. Pterosaurio de tamaño medio.",
        desc: "Llevado a Isla Nublar para Fase 2. Pterosaurio de tamaño medio con adaptaciones para vuelo sostenido en ambientes tropicales.",
        extra: "El Cearadactylus atrox era un pterosaurio del Cretácico inferior sudamericano con dientes entrelazados como una trampa para peces. InGen mejoró su capacidad pulmonar con ADN de fragata magnífica para sostener el vuelo en condiciones de calor y humedad tropical. Su comportamiento en cautiverio fue altamente territorial, siendo incompatible con otras especies de pterosaurios en el mismo espacio."
    },
    {
        name: "Ceratosaurus",
        key: "CR-77394",
        family: "Ceratosauridae",
        diet: "carnivoro",
        dietLabel: "CARNÍVORO",
        height: "2 m",
        length: "6 m",
        weight: "1,000 kg",
        location: "Isla Sorna",
        emoji: "🦖",
        ingen: "Clonado durante Re-Genesis. Adaptación a ambientes pantanosos.",
        desc: "Clonado durante la operación Re-Genesis. Mostró adaptación a ambientes pantanosos y resistencia bacteriana elevada.",
        extra: "El Ceratosaurus nasicornis del Jurásico tardío es uno de los terópodos más primitivos conocidos, caracterizado por el cuerno nasal óseo. Los especímenes InGen desarrollaron una resistencia bacteriana 3 veces superior a la registrada en cualquier reptil vivo, posiblemente resultado de ADN de relleno de cocodrilo del Nilo. Tendieron a evitar a otros grandes depredadores, prefiriendo zonas pantanosas ricas en anfibios y peces."
    },
    {
        name: "Chasmosaurus",
        key: "CH-60329",
        family: "Ceratopsidae",
        diet: "herbivoro",
        dietLabel: "HERBÍVORO",
        height: "2 m",
        length: "5 m",
        weight: "3,000 kg",
        location: "Isla Sorna",
        emoji: "🐘",
        ingen: "Clonado en Sorna. Herbívoro con comportamiento gregario.",
        desc: "Clonado en Sorna. Herbívoro con comportamiento gregario y uso de gola ósea para exhibición y defensa.",
        extra: "El Chasmosaurus belli del Cretácico tardío de Norteamérica tenía una de las golas más largas en proporción al cuerpo de todos los ceratopsianos. Esta estructura, cubierta de piel vascularizada, servía para termorregulación, exhibición sexual y señalización social. Los ejemplares InGen mostraron patrones de coloración en la gola más vibrantes que cualquier registro fósil podría sugerir, lo que indica modificación genética deliberada para fines estéticos."
    },
    {
        name: "Compsognathus",
        key: "JD-91173",
        family: "Compsognathidae",
        diet: "carnivoro",
        dietLabel: "CARNÍVORO",
        height: "30 cm",
        length: "1 m",
        weight: "6 kg",
        location: "Isla Sorna / Isla Nublar",
        emoji: "🦎",
        ingen: "Al menos diez ejemplares se infiltraron en Nublar. Toxinas salivales leves.",
        desc: "Clonado en Sorna. Al menos diez ejemplares se infiltraron en Nublar. Presentan toxinas salivales leves que inducen parálisis temporal.",
        extra: "El Compsognathus longipes del Jurásico tardío de Europa era uno de los dinosaurios más pequeños conocidos. InGen incorporó glándulas salivales modificadas con secreciones peptídicas derivadas de ADN de musaraña de dientes rojos, resultando en una saliva que induce parálisis muscular temporal en mamíferos de hasta 40 kg. La mordedura de un solo ejemplar puede ser incapacitante; la mordedura de una manada resulta fatal. Se han registrado ataques mortales a humanos."
    },
    {
        name: "Concavenator",
        key: "CV-49210",
        family: "Carcharodontosauridae",
        diet: "carnivoro",
        dietLabel: "CARNÍVORO",
        height: "2.5 m",
        length: "6 m",
        weight: "3,000 kg",
        location: "Isla Matanceros",
        emoji: "🦖",
        ingen: "Clonado en Isla Matanceros. Joroba dorsal con irrigación vascular significativa.",
        desc: "Clonado en Isla Matanceros. La joroba dorsal mostró irrigación vascular significativa, posiblemente para almacenamiento energético.",
        extra: "El Concavenator corcovatus del Cretácico inferior de España es notable por su joroba ósea previa a la cadera, cuya función es debatida. Los análisis de los especímenes InGen mediante termografía revelaron que la joroba actúa como radiador termal durante actividad intensa, disipando hasta el 40% del exceso de calor metabólico y permitiendo períodos de actividad prolongados en comparación con otros grandes terópodos."
    },
    {
        name: "Corythosaurus",
        key: "CY-58321",
        family: "Hadrosauridae",
        diet: "herbivoro",
        dietLabel: "HERBÍVORO",
        height: "3.5 m",
        length: "9 m",
        weight: "4,000 kg",
        location: "Isla Sorna / Isla Matanceros",
        emoji: "🎺",
        ingen: "Clonado durante Re-Genesis. Comunicación por resonancia craneal.",
        desc: "Clonado durante Re-Genesis. Estudios acústicos sugieren comunicación por resonancia craneal.",
        extra: "El Corythosaurus casuarius del Cretácico tardío tenía una cresta cefálica hueca en forma de casco que actuaba como cámara de resonancia. Los ejemplares InGen fueron objeto de estudios acústicos que revelaron un repertorio de al menos 14 vocalizaciones distintas con frecuencias entre 20 Hz y 800 Hz, incluyendo infrasónicas que se propagan a través del suelo. Se documentó comunicación entre grupos separados por hasta 3 kilómetros."
    },
    {
        name: "Cryolophosaurus",
        key: "CRY-76284",
        family: "Dilophosauridae",
        diet: "carnivoro",
        dietLabel: "CARNÍVORO",
        height: "3.7 m",
        length: "9 m",
        weight: "2,200 kg",
        location: "Isla Matanceros",
        emoji: "🦖",
        ingen: "Clonado en Isla Matanceros. Alta agresividad.",
        desc: "Clonado en Isla Matanceros. Mostró agresividad elevada y adaptabilidad a climas templados.",
        extra: "El Cryolophosaurus ellioti del Jurásico temprano antártico es el dinosaurio terópodo más completo encontrado en la Antártida. Su cresta frontal perpendicular al cráneo le valió el apodo de 'Elvisaurus'. Los especímenes InGen mostraron un metabolismo activo en rangos de temperatura de 5-35°C, significativamente más amplio que otros terópodos clonados, y niveles de agresividad intraespecífica que resultaron en la muerte de uno de los tres ejemplares originales."
    },
    {
        name: "Deinosuchus",
        key: "DN-87543",
        family: "Alligatoridae",
        diet: "carnivoro",
        dietLabel: "CARNÍVORO",
        height: "1.5 m (lomo)",
        length: "12 m",
        weight: "4,500 kg",
        location: "Isla Sorna",
        emoji: "🐊",
        ingen: "Clonado en Sorna. Reptil gigante con comportamiento territorial acuático.",
        desc: "Clonado en Sorna. Reptil gigante con fuerza mandibular extrema y comportamiento territorial acuático.",
        extra: "El Deinosuchus rugosus del Cretácico tardío de Norteamérica era un crocodyliforme gigante capaz de cazar dinosaurios adultos. Con una longitud estimada de 10-12 m y una fuerza de mordida estimada en 18,000 N, era el superdepredador acuático de su ecosistema. El espécimen InGen fue ubicado en el lago principal de Sorna, donde eliminó múltiples especímenes de Gallimimus que se acercaban a beber. Considerado el organismo más peligroso de la isla por los equipos de campo."
    },
    {
        name: "Diabloceratops",
        key: "DC-68129",
        family: "Ceratopsidae",
        diet: "herbivoro",
        dietLabel: "HERBÍVORO",
        height: "1.8 m",
        length: "5 m",
        weight: "1,300 kg",
        location: "Isla Matanceros",
        emoji: "🐘",
        ingen: "Clonado en Isla Matanceros. Cornamenta desarrollada para defensa.",
        desc: "Clonado en Isla Matanceros. Cornamenta desarrollada para defensa y competencia intraespecífica.",
        extra: "El Diabloceratops eatoni del Cretácico tardío de Utah es una de las formas más primitivas de los ceratopsianos con gola. Sus cuernos parietales curvados hacia arriba son únicos entre los ceratópsidos. Los ejemplares InGen mostraron una fase de exhibición de gola cromática antes de los combates intraespecíficos, con vasos sanguíneos superficiales que enrojecen la membrana de la gola en señal de alerta o agresión territorial."
    },
    {
        name: "Dilophosaurus",
        key: "RD-17307",
        family: "Dilophosauridae",
        diet: "carnivoro",
        dietLabel: "CARNÍVORO",
        height: "2 m",
        length: "6 m",
        weight: "400 kg",
        location: "Isla Nublar / Isla Sorna",
        emoji: "💉",
        ingen: "Conservó glándulas productoras de veneno con proteínas modificadas.",
        desc: "Llevado a Nublar para exhibición. Algunos permanecieron en Sorna. Conservó glándulas productoras de veneno con proteínas modificadas.",
        extra: "El Dilophosaurus wetherilli del Jurásico temprano de Norteamérica no tiene evidencia fósil de producción de veneno, pero InGen introdujo glándulas venénicas modificadas a partir de ADN de cobra escupidora de Mozambique y lagarto monstruo de Gila. El veneno producido es una neurotoxina que causa ceguera temporal, espasmos musculares y posteriormente shock sistémico. El alcance de proyección documentado es de hasta 4 metros. Varios operativos de InGen resultaron heridos en Sorna."
    },
    {
        name: "Dimetrodon",
        key: "INGEN-DIM-020",
        family: "Sphenacodontidae",
        diet: "carnivoro",
        dietLabel: "CARNÍVORO",
        height: "1.8 m",
        length: "4.5 m",
        weight: "226 kg",
        location: "Isla Nublar",
        emoji: "🦎",
        ingen: "Sinápsido con vela dorsal altamente vascularizada. Llevado a Nublar para Fase 2.",
        desc: "Llevado a Nublar para Fase 2. Sinápsido con vela dorsal altamente vascularizada.",
        extra: "El Dimetrodon limbatus del Pérmico temprano de Norteamérica es técnicamente un sinápsido, más emparentado con los mamíferos que con los dinosaurios. Su icónica vela dorsal sostenida por largas espinas neurales tenía función termorreguladora. InGen lo incluyó en la Fase 2 de Jurassic Park para diversidad exhibicional, siendo el único no-dinosaurio del catálogo original. Los registros post-1993 de este espécimen están clasificados."
    },
    {
        name: "Diplodocus",
        key: "DP-88472",
        family: "Diplodocidae",
        diet: "herbivoro",
        dietLabel: "HERBÍVORO",
        height: "4 m (hombros)",
        length: "27 m",
        weight: "15,000 kg",
        location: "Isla Matanceros",
        emoji: "🦕",
        ingen: "Clonado en Isla Matanceros. Gran herbívoro de metabolismo elevado.",
        desc: "Clonado en Isla Matanceros. Gran herbívoro de metabolismo elevado y necesidad extensiva de territorio.",
        extra: "El Diplodocus hallorum del Jurásico tardío de Norteamérica fue uno de los dinosaurios más largos conocidos. Su cola delgada podía utilizarse como látigo sónico supersónico. Los estudios de los especímenes InGen confirmaron que el extremo de la cola puede romper la barrera del sonido localmente, generando un chasquido de aproximadamente 200 dB a 1 metro. Este comportamiento defensivo fue documentado ante la aproximación de depredadores grandes."
    },
    {
        name: "Dracorex",
        key: "DR-91584",
        family: "Pachycephalosauridae",
        diet: "herbivoro",
        dietLabel: "HERBÍVORO",
        height: "1.5 m",
        length: "4 m",
        weight: "800 kg",
        location: "Isla Matanceros",
        emoji: "🐉",
        ingen: "Clonado en Isla Matanceros. Cráneo reforzado para embestidas defensivas.",
        desc: "Clonado en Isla Matanceros. Presentó cráneo reforzado para embestidas defensivas.",
        extra: "El Dracorex hogwartsia del Cretácico tardío de Norteamérica (cuyo nombre fue sugerido por niños fans de Harry Potter) tiene un cráneo plano con protuberancias y espinas que lo hacen único entre los paquicefalosáuridos. Algunos paleontólogos lo consideran una forma juvenil de Pachycephalosaurus. Los ejemplares InGen mostraron un comportamiento de embestida cefálica de hasta 24 km/h, capaz de dañar estructuralmente muros de 15 cm de concreto."
    },
    {
        name: "Dryosaurus",
        key: "DR-33451",
        family: "Dryosauridae",
        diet: "herbivoro",
        dietLabel: "HERBÍVORO",
        height: "1.5 m",
        length: "3 m",
        weight: "80 kg",
        location: "Isla Sorna",
        emoji: "🦘",
        ingen: "Clonado en Sorna. Alta velocidad y comportamiento evasivo.",
        desc: "Clonado en Sorna. Herbívoro pequeño con alta velocidad y comportamiento evasivo.",
        extra: "El Dryosaurus altus del Jurásico tardío era un ornitópodo bípedo de movimientos muy rápidos. Su construcción ligera y largas patas traseras le permitían alcanzar velocidades estimadas de 40-50 km/h. Los especímenes InGen formaron grupos de alerta coordinada con Gallimimus, respondiendo ante la misma señal de alarma y actuando como sistema de detección temprana mutualista ante depredadores. Esta coordinación interespecífica no había sido predicha por los etólogos."
    },
    {
        name: "Edmontosaurus",
        key: "EM-83042",
        family: "Hadrosauridae",
        diet: "herbivoro",
        dietLabel: "HERBÍVORO",
        height: "3 m",
        length: "12 m",
        weight: "4,000 kg",
        location: "Isla Sorna",
        emoji: "🐄",
        ingen: "Clonado en Sorna. Migraciones internas estacionales.",
        desc: "Clonado en Sorna. Mostró migraciones internas estacionales.",
        extra: "El Edmontosaurus annectens del Cretácico tardío de Norteamérica es uno de los hadrosáuridos más conocidos, con cresta craneal baja. Se han preservado momias naturales de esta especie que revelan su piel escamosa y musculatura. Los especímenes InGen de Sorna desarrollaron ciclos de migración interna siguiendo patterns de vegetación estacional de la isla, recorriendo hasta 200 km anuales en grupos de 40-70 individuos."
    },
    {
        name: "Elasmosaurus",
        key: "EL-33256",
        family: "Elasmosauridae",
        diet: "piscivoro",
        dietLabel: "PISCÍVORO",
        height: "2 m",
        length: "14 m",
        weight: "3,000 kg",
        location: "Isla Matanceros (marina)",
        emoji: "🐍",
        ingen: "Clonado en Isla Matanceros para instalaciones marinas. Cuello largo altamente flexible.",
        desc: "Clonado en Isla Matanceros para instalaciones marinas. Cuello largo altamente flexible.",
        extra: "El Elasmosaurus platyurus del Cretácico tardío de Norteamérica es un plesiosáurido cuyo cuello constituye la mitad de su longitud total, con 71 vértebras cervicales. InGen construyó instalaciones marinas en la costa norte de Isla Matanceros para albergar sus especímenes marinos. El ejemplar de Elasmosaurus fue documentado sumergiéndose a profundidades de hasta 180 m en pruebas de buceo monitoreado. Su destino tras el cierre de Re-Genesis es desconocido."
    },
    {
        name: "Euplocephalus",
        key: "INGEN-EUP-026",
        family: "Ankylosauridae",
        diet: "herbivoro",
        dietLabel: "HERBÍVORO",
        height: "1.8 m",
        length: "6 m",
        weight: "2,500 kg",
        location: "Isla Nublar",
        emoji: "🛡️",
        ingen: "Llevado a Nublar para Fase 2. Armadura ósea avanzada.",
        desc: "Llevado a Nublar para Fase 2. Armadura ósea avanzada y comportamiento defensivo.",
        extra: "El Euoplocephalus tutus del Cretácico tardío de Norteamérica era un anquilosáurido completo: incluso sus párpados eran óseos. Su maza caudal podía generar fuerzas de impacto de hasta 6,000 N. Los especímenes InGen destinados a Nublar para la Fase 2 nunca llegaron a ser exhibidos públicamente debido al incidente de 1993. Su rastro se pierde en los registros post-evacuación de la isla."
    },
    {
        name: "Gallimimus",
        key: "GA-22779",
        family: "Ornithomimidae",
        diet: "omnivoro",
        dietLabel: "OMNÍVORO",
        height: "3 m",
        length: "4.7 m",
        weight: "450 kg",
        location: "Isla Nublar / Isla Sorna / Isla Matanceros",
        emoji: "🏃",
        ingen: "Presente en múltiples islas. Velocidad estimada superior a 60 km/h.",
        desc: "Presente en Nublar, Sorna y Matanceros. Velocidad estimada superior a 60 km/h.",
        extra: "El Gallimimus bullatus del Cretácico tardío asiático era uno de los dinosaurios más rápidos conocidos, con estimaciones de velocidad de 42-56 km/h en adultos. Los especímenes InGen alcanzaron velocidades máximas medidas de 64 km/h en sprint de 100 metros. Es la especie más numerosa documentada en todas las instalaciones InGen. En Sorna, las manadas alcanzaron tamaños de hasta 200 individuos, constituyendo la biomasa animal dominante de la isla."
    },
    {
        name: "Geosternbergia",
        key: "INGEN-GEO-028",
        family: "Pteranodontidae",
        diet: "piscivoro",
        dietLabel: "PISCÍVORO",
        height: "1.8 m (de pie)",
        length: "7.5 m (envergadura)",
        weight: "22 kg",
        location: "Isla Sorna",
        emoji: "🦅",
        ingen: "Clonada en Sorna. Pterosaurio de gran envergadura.",
        desc: "Clonada en Sorna. Pterosaurio de gran envergadura y vuelo planeador.",
        extra: "Geosternbergia sternbergi del Cretácico tardío de Norteamérica es uno de los pterosaurios más grandes del género Pteranodon, con una cresta craneal inversa más pequeña que el macho típico (indicando hembra). Los especímenes de Sorna anidaron en los acantilados del norte de la isla. Su comportamiento con intrusos humanos fue documentado como altamente defensivo, con ataques coordinados en pareja para proteger nidos."
    },
    {
        name: "Giganotosaurus",
        key: "GN-49723",
        family: "Carcharodontosauridae",
        diet: "carnivoro",
        dietLabel: "CARNÍVORO",
        height: "4.5 m",
        length: "13 m",
        weight: "8,000 kg",
        location: "Isla Matanceros",
        emoji: "🦖",
        ingen: "Clonado en Isla Matanceros. Diseñado como depredador ápice alternativo al T. rex.",
        desc: "Clonado en Isla Matanceros. Diseñado como depredador ápice alternativo al Tyrannosaurus.",
        extra: "El Giganotosaurus carolinii del Cretácico temprano de Argentina es uno de los terópodos más grandes conocidos, posiblemente superando al T. rex en longitud aunque con una estructura craneal más delgada y un cerebro menor. InGen lo clonó como alternativa para el 'Proyecto Chaos' en Matanceros, donde el espacio y los recursos naturales eran más limitados. Los estudios de comportamiento revelaron estrategias de caza cooperativa entre dos o tres ejemplares juveniles."
    }
];
